### ISSUE TITLE
Lack of IPv6 support

### ISSUE THREAD

**Issue by bert128** [lgandx/Responder#102]
Responder does not listen on IPv6 sockets, or to the IPv6 multicast addresses.

MacOSX by default sends MDNS requests to the local network using IPv6:

```
13:31:16.759829 IP6 fe80::817:ef87:f186:5ccc.5353 > ff02::fb.5353: 0 A (QU)? blah.local. (28)
13:31:17.337053 IP6 fe80::1010:92af:a5db:30a8.5353 > ff02::fb.5353: 0 [4a] [3q] [1au] PTR (QM)? _companion-link._tcp.local. PTR (QM)? _homekit._tcp.local. PTR (QM)? _sleep-proxy._udp.local. (231)
```

It seems to do this even if IPv6 is not actually enabled on the local network. The link local addresses only depend upon the hosts themselves having ipv6 enabled, and they will communicate using this over the local segment even if there is no upstream routing.

**Comment by lgandx** [comment]
Unfortunately, Responder provide very limited OsX support. You could always send a pull request, and if approved I'll push it on the repo. 
Cheers
