### ISSUE TITLE
Should switch to Python 3

### ISSUE THREAD

**Issue by sbrun** [lgandx/Responder#104]
Python 2.x will no longer be supported by their upstream developers in 2020. Thus Debian developers are actively removing Python 2 support in Debian Testing with the goal of getting rid of Python 2 in Debian 11 (bullseye).
Kali is tracking Debian Testing and is thus affected by this. You should consider to switch responder to Python 3.

FWIW this is tracked in https://gitlab.com/kalilinux/packages/responder/issues/1 on the Kali side.

**Comment by lgandx** [comment]
Thanks for this issue. I want to have support for both python versions and I've been working on some code recently to accomplish just that. Changes from python2 to python3 are pretty significant, especially on how network strings are interpreted and handled, calculations, and etc between python 2 and 3. This will requires a major code refactoring to support both versions...
Will see how it goes over the next months and will push an update when possible.
Cheers

**Comment by lgandx** [comment]
Responder now supports py2 and py3.

**Comment by yellow-starburst** [comment]
Closed issue

**Comment by blshkv** [comment]
Please release a new version so we could bump it.

**Comment by q2dg** [comment]
This issue still formally remains open...

**Comment by lberrymage** [comment]
There are a few bugs yet that prevent `responder` from running on Python 3. For example:
```
$ responder -I enp2s0
                                         __
  .----.-----.-----.-----.-----.-----.--|  |.-----.----.
  |   _|  -__|__ --|  _  |  _  |     |  _  ||  -__|   _|
  |__| |_____|_____|   __|_____|__|__|_____||_____|__|
                   |__|

           NBT-NS, LLMNR & MDNS Responder 3.0.0.0

  Author: Laurent Gaffie (laurent.gaffie@gmail.com)
  To kill this script hit CTRL-C

Traceback (most recent call last):
  File "Responder.py", line 58, in <module>
    settings.Config.populate(options)
  File "/usr/share/responder/settings.py", line 192, in populate
    self.Bind_To         = utils.FindLocalIP(self.Interface, self.OURIP)
  File "/usr/share/responder/utils.py", line 138, in FindLocalIP
    s.setsockopt(socket.SOL_SOCKET, 25, Iface+'\0')
TypeError: a bytes-like object is required, not 'str'
$

**Comment by OJ** [comment]
While we're at it, another issue that exists on Python3 is when files are served via `Serve*File` packets (such as `ServeHtmlFile`). From my testing, if you have a file on disk that contains the following:
``` html
<html>hi!</html>
```
Python3 will serve up the following instead:
``` html
b'<html>hi!</html>'
```

**Comment by lgandx** [comment]
Thanks for your report OJ, this will be fixed in the next commit.

**Comment by blshkv** [comment]
please release a new version with the fix

**Comment by lgandx** [comment]
Already done.

**Comment by blshkv** [comment]
sorry, can't find it. https://github.com/lgandx/Responder/releases still shows 3.0.0?

**Comment by lgandx** [comment]
Git clone the repo, it wasn't pushed to a release yet.

**Comment by blshkv** [comment]
well, I'm asking for a release so that all distros can pick it up
