### ISSUE TITLE
Interface option -> TypeError 

### ISSUE THREAD

**Issue by chamaillard** [lgandx/Responder#115]
I got a crash with Python 3.6.9 
The simple command "python3 ./Responder.py -A -I eth1" ended up with the following error:

`TypeError : a bytes-like object is required, not 'str'`
for the file /Responder/utils.py line 138

i fixed it by changing
`s.setsockopt(socket.SOL_SOCKET, 25, Iface+'\0')`
to
`s.setsockopt(socket.SOL_SOCKET, 25, str(Iface+'\0').encode('utf-8'))`

Well, not used to submit issues, hope that's good enough

**Comment by lgandx** [comment]
Fixed, thanks for your report!
