### ISSUE TITLE
Static challenge parse error and failure

### ISSUE THREAD

**Issue by s3c** [lgandx/Responder#122]
I'm trying to capture an LM hash and crack using rainbow tables, but setting a static challenge breaks due to a parsing error, guessing python2 to python3 conversion artifact:

```
Traceback (most recent call last):
  File "./Responder.py", line 58, in <module>
    settings.Config.populate(options)
  File "/usr/share/responder/settings.py", line 218, in populate
    self.Challenge += self.NumChal[i:i+2].decode("hex")
AttributeError: 'str' object has no attribute 'decode'
```

Updating that line was easy enough, and the correct challenge is shown after launch:

`self.Challenge += hex(int(self.NumChal[i:i+2]))`

The problem is that after making this change, no hashes are captured anymore, even from hosts that work when a random challenge is given. Any ideas?

**Comment by s3c** [comment]
Looks like I have some weird version mismatch stuff going on, closing.

**Comment by fsacer** [comment]
I'm also having the same issue still. Maybe some source needs to be changed for this?
