### ISSUE TITLE
RunFinger.py not returning anything

### ISSUE THREAD

**Issue by m33s33ks** [lgandx/Responder#126]
Hello there
I'm trying to use RunFinger.py on my AD Lab and no matter what I try it's not returning anything.
When I start it without any arguments I get the -i Mandatory option is missing text.
The version was 0.7 on an updated Kali and 1.0 each time with the exact same results:
Here is what I tried:
`python RunFinger.py -i 192.168.190.1/24
`
`python RunFinger.py --ip=192.168.190.1/24
`

I tried both with python3 and also with just a single IP.  There is no error. The cursor blinks and then I'm back on a newline in bash.

**Comment by braimee** [comment]
Same issue as @m33s33ks here on a fresh Kali box and fresh install of Responder toolkit.  Tried a single IP and various subnets.  Tool just hangs for a few seconds like it's thinking hard....then no results returned.

**Comment by lgandx** [comment]
I'm not sure how Kali's version is implemented.
It works well on the latest version provided on this repository:
root@lgandx-8:~/Responder/tools# python RunFinger.py -i 192.168.0.0/24
Retrieving information for 192.168.0.167...
SMB signing: False
Null Sessions Allowed: True
Server Time: 2020-08-17 15:29:42
OS version: 'Windows 7 Professional 7601 Service Pack 1'
Lanman Client: 'Windows 7 Professional 6.1'
Machine Hostname: 'WIN-VR9EK1SGTG5'
This machine is part of the 'WORKGROUP' domain
RDP port open: 'False'
