### ISSUE TITLE
Fails to start DNS module when dnsmasq is running on localhost

### ISSUE THREAD

**Issue by bmorgenthaler** [lgandx/Responder#127]
So the instructions say to stop dnsmasq but why should that be an issue when it's running on localhost and you can specify the interface and listening IP for Responder.

Shouldn't Responder be able to listen on the specific interfaces IP without having interference from postfix running on localhost:25 or dnsmasq on localhost:53?

**Comment by lgandx** [comment]
Usually dnsmasq will be listening on 0.0.0.0:53, that's why it is recommended to stop dnsmasq.
Responder has the ability to listen on a specific interface and if no services are running on these ports Responder will not throw any errors.
