### ISSUE TITLE
Responder not showing NTLMv2 SSP hashes for certains clients (ex: net rpc, Impacket scripts, smbclient)

### ISSUE THREAD

**Issue by jmbesnard** [lgandx/Responder#128]
Hi,

I've noticed that Responder will not print NTLMv2 SSP hashes when gettings hits from certains tools (for both python2 and 3).

The following commands shall help reproducing that easily (with random usernames to bypass the cache of Responder) :

IP=192.168.1.6
USER=$(date |md5sum|cut -b1-8)
smbclient -U smbclient$USER%smbclient -L $IP

USER=$(date |md5sum|cut -b1-8)
wmiexec.py   wmiexec$USER:wmiexec@$IP

USER=$(date |md5sum|cut -b1-8)
smbexec.py   smbexec$USER:smbexec@$IP

USER=$(date |md5sum|cut -b1-8)
net rpc share list -S $IP -U netrpc$USER%netrpc

Providing the network capture to PCredz shows the corresponding NetNTLMv2 SSP hashes (thus indicating that everything works fine from a protocol standpoint) :

protocol: tcp 192.168.1.7:34842 > 192.168.1.6:445
NTLMv2 complete hash is: smbclienta79e5493::WORKGROUP:1122334455667788:2996BDFD1966F90ABD7148233D0A437B:010100000000000022C346ED3A56D60107CD518EA03D6B2A0000000002000A0053004D0042003100320001000A0053004D0042003100320004000A0053004D0042003100320003000A0053004D0042003100320005000A0053004D0042003100320008003000300000000000000000000000000000008D2AE6A099480DEBBE97E86FE713FB1049AFB3D885863B62331922C21D46A99C0A001000000000000000000000000000000000000900200063006900660073002F003100390032002E003100360038002E0031002E00360000000000

protocol: tcp 192.168.1.7:34846 > 192.168.1.6:445
NTLMv2 complete hash is: wmiexec5c2f0186:::1122334455667788:377D908636DC0A5FD27EFD9FB26746B3:0101000000000000001C4BEE3A56D6014A695A35384678520000000002000A0053004D0042003100320001000A0053004D0042003100320004000A0053004D0042003100320003000A0053004D0042003100320005000A0053004D004200310032000900140063006900660073002F0053004D0042003100320007000800001C4BEE3A56D6010000000000000000

protocol: tcp 192.168.1.7:34850 > 192.168.1.6:445
NTLMv2 complete hash is: smbexec5c2f0186:::1122334455667788:CDC9FD9F35E7C7382047BC99EF90DFBD:0101000000000000001C4BEE3A56D6017A5A75737734304A0000000002000A0053004D0042003100320001000A0053004D0042003100320004000A0053004D0042003100320003000A0053004D0042003100320005000A0053004D004200310032000900140063006900660073002F0053004D0042003100320007000800001C4BEE3A56D6010000000000000000

protocol: tcp 192.168.1.7:34852 > 192.168.1.6:445
NTLMv2 complete hash is: netrpc5c2f0186::WORKGROUP:1122334455667788:502B8D14A92648A9F142C40B7A08DCAF:01010000000000007A59E8EE3A56D601A0B3159D99798FEE0000000002000A0053004D0042003100320001000A0053004D0042003100320004000A0053004D0042003100320003000A0053004D0042003100320005000A0053004D004200310032000800300030000000000000000000000000000000282D988D618D74E42595D5FD7073311CBC06F902AC44B922FEDB83CC486A82200A001000000000000000000000000000000000000900200063006900660073002F003100390032002E003100360038002E0031002E00360000000000

Looking through the different commits, this behavior seems to have been introduced here :
commit 85d7974513a9b6378ed4c0c07a7dd640c27ead9b
Author: lgandx <laurent.gaffie@gmail.com>
Date:   Fri Sep 9 02:50:39 2016 -0300

    Added SMBv2 support enabled by default.
 
I've had a quick look at the code and observed that part of the answer can be found at line 241 of servers/SMB.py
				if data[16:18] == b'\x01\x00' and GrabMessageID(data)[0:1] == b'\x02' and data[4:5] == b'\xfe':
Indeed, when using Impackets's wmiexec.py and smbexec.py, the MessageID is 0x03 and not 0x02. Although I am not very familiar with the protocol, I'd guess that x02 and x03 should be considered in that if statement.

As for smbclient and net rpc, the problem seems to be at line 236 where a concatenation throws an exception
packet1 = str(head)+str(t)

Regards,

Jean-Michel Besnard

**Comment by lgandx** [comment]
Excellent report!
I checked the code and it seems like some clients doesn't count the message ID the same way than other.
Fix implemented in next commit. 
Thank you Jean-Michel

**Comment by marineMB** [comment]
Hi,

I can't find the commit that fixed this issue and it still doesn't work for me.
If I remove GrabMessageID(data)[0:1] == b'\x02',  line 241 of servers/SMB.py as Jean-Michel said, I can see my NTLMv2 hashes.

Bests,
Marine
