### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by enoir3** [lgandx/Responder#129]
Hi all, ran into an error I've never seen before:
![image](https://user-images.githubusercontent.com/65781895/89896824-161bcd00-dbac-11ea-8db3-d83db65652c9.png)

I executed Responder with: `sudo python3 Responder.py -I eth0 -vFW`

I saw the error first when using Responder installed through apt.  Then I cloned the GitHub repo around 0815 am on 8/11, to make absolute sure I have the latest version and am still receiving the error.  The error above happens for several hosts, so I chose to show just one of the IPs.  My machine has a static IP on the same network segment.  As a side note (may be unrelated), the local network is very, very noisy, so I thought maybe there is too much input and sqlite is having issues adding that much data at once maybe?

Here is a snip of the version and "GUI" settings.  All settings are default, other than using the vFW flags:
![image](https://user-images.githubusercontent.com/65781895/89897769-8c6cff00-dbad-11ea-8c11-d840714e9138.png)

**Comment by lgandx** [comment]
Hi, 
Please run "rm Responder.db" in Responder folder and launch Responder again.
This happens when an updated version runs with an old DB. 
Regards,

**Comment by ablito19** [comment]
Hello, i reopen ticket.
I got same error and try your fix but not working

**Comment by sternyx** [comment]
Hoping to reopen this ticket as I am also getting the same error. This happens when trying to store hashes or just in analyze mode.

**Comment by BustedSec** [comment]
@sternyx can you confirm you deleted the Responder.db file and also check if you are running it from the folder and launching the program with sudo and using the python3 interpreter?

**Comment by sternyx** [comment]
I have removed the db as well as done a fresh install both with Kali apt and a git clone. All versions are latest. Logs have been cleared as well. Python3 is latest version as well. First time having seen this in all honesty. 

I do have a special character it seems that the sqlite may not like processing. 

![2023-09-06 12_57_24-](https://github.com/lgandx/Responder/assets/115005418/a20cfe17-cbed-415f-b918-d391b0a947a0)

**Comment by sternyx** [comment]
I have removed the db as well as done a fresh install both with Kali apt and a git clone. All versions are latest. Logs have been cleared as well. Python3 is latest version as well. First time having seen this in all honesty.

I do have a special character it seems that the sqlite may not like processing.

![2023-09-06 12_57_24-](https://github.com/lgandx/Responder/assets/115005418/7667f676-cd45-4d43-bf2e-96afd5942e54)
