### ISSUE TITLE
Is smbrelayx still required?

### ISSUE THREAD

**Issue by blindfuzzy** [lgandx/Responder#13]
Is smbrelayx still required with the new multi-relay stuff?

**Comment by lgandx** [comment]
MultiRelay is a standalone tool and is autonomous.
smbrelayx is another tool you can also use, if you want to.

**Comment by blindfuzzy** [comment]
Normally I run smbrelayx with Responder. If I don't have to do that and get the same outcome of passing the hash with just Responder and the multi-relay included with Responder then i'm sold.

**Comment by lgandx** [comment]
Try ./Responder.py -I eth0 -rv on one screen and ./tools/MultiRelay.py -t Target -u ALL on another one.
Let me know we you get a  MultiRelay shell :)

**Comment by blindfuzzy** [comment]
Just deleted the old Responder....I'm sold on this new one. So much easier/faster.
