### ISSUE TITLE
No module named 'UserDict'

### ISSUE THREAD

**Issue by Rourke101** [lgandx/Responder#137]
This was supposed to be fixed:
https://github.com/lgandx/Responder/issues/119

So, Why am I getting this?

I try to check if I was using the wrong Python, but the script forces python3.

```
kali@kali:~$ responder-MultiRelay 
/usr/share/responder/tools/MultiRelay.py:418: SyntaxWarning: "is not" with a literal. Did you mean "!="?                                                        
  if data.find("NTLM") is not -1:                                                                                                                               
/usr/share/responder/tools/MultiRelay.py:423: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if data.find("NTLM") is not -1:
Traceback (most recent call last):
  File "/usr/share/responder/tools/MultiRelay.py", line 39, in <module>
    from MultiRelay.RelayMultiCore import *
  File "/usr/share/responder/tools/MultiRelay/RelayMultiCore.py", line 32, in <module>
    from SMBFinger.Finger import ShowSmallResults
  File "/usr/share/responder/tools/SMBFinger/Finger.py", line 21, in <module>
    from .odict import OrderedDict
  File "/usr/share/responder/tools/SMBFinger/odict.py", line 1, in <module>
    from UserDict import DictMixin
ModuleNotFoundError: No module named 'UserDict'
kali@kali:~$ sudo apt install responder 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
responder is already the newest version (3.0.1.0-0kali1).
```

**Comment by mlgualtieri** [comment]
I ran into this tonight myself.  I did this to fix:

Remove:
```
from .odict import OrderedDict
```
Add:
```
try:
    from collections import OrderedDict
except:
    from .odict import OrderedDict
```

**Comment by Rourke101** [comment]
Thank you!
I edited "/usr/share/responder/tools/SMBFinger/Finger.py" and made the change. It gives me a couple of warnings but I got something:

`$ responder-MultiRelay 
/usr/share/responder/tools/MultiRelay.py:418: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if data.find("NTLM") is not -1:
/usr/share/responder/tools/MultiRelay.py:423: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if data.find("NTLM") is not -1:

-t Mandatory option is missing, please provide a target.

Usage: 
responder-MultiRelay -t 10.20.30.40 -u Administrator lgandx admin
responder-MultiRelay -t 10.20.30.40 -u ALL

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -t 10.20.30.45        Target server for SMB relay.
  -p 8081               Additional port to listen on, this will relay for
                        proxy, http and webdav incoming packets.
  -u, --UserToRelay     Users to relay. Use '-u ALL' to relay all users.
  -c whoami, --command=whoami
                        Single command to run (scripting)                                                                                                                                                  
  -d, --dump            Dump hashes (scripting)`

**Comment by HBT89** [comment]
I don't think Issue #119 is actually fixed, just closed
