### ISSUE TITLE
MultiRelay shell commands fail

### ISSUE THREAD

**Issue by bl1tzw0lf** [lgandx/Responder#141]
I've used several versions of responder the last year and continue having problems getting multirelay interactive shell commands to work ... typical example:

+++++++++++++++++++++++++++
C:\Windows\system32\:#ipconfig /all
[+] Failed to start the service.

[+] Something went wrong, try something else.

C:\Windows\system32\:#dump
The Windows Remote Registry Service is sleeping, waking it up...
BootKey: 1f3e95c1d0f202315f5927fdc9d8853c
[+] Something went wrong, try something else.

C:\Windows\system32\:#mimi sekurlsa::logonpasswords
File size: 746.50KB
[================================================================================] 100.0%
Uploaded in: -0.926 seconds
[+] Failed to start the service.

[+] Something went wrong, try something else.
[+] Something went wrong while calling mimikatz. Maybe it's a 32bits system? Try mimi32.
C:\Windows\system32\:#mimi32 sekurlsa::logonpasswords
File size: 598.50KB
[================================================================================] 100.0%
Uploaded in: -0.921 seconds
[+] Failed to start the service.

[+] Something went wrong, try something else.
[+] Something went wrong while calling mimikatz. Maybe it's a 32bits system? Try mimi32.
C:\Windows\system32\:#

Am I missing something?

**Comment by lgandx** [comment]
Hi
Mimikatz probably got flagged by an AV and deleted.
