### ISSUE TITLE
No module named Crypto.Hash

### ISSUE THREAD

**Issue by n8zwn** [lgandx/Responder#144]
In Kali 2020.3, I am unable to run MultiRelay. I keep getting no module named Crypto.Hash. I am using Python3 and I have installed Python3-crypto. Does this not support Python3? I couldn't find anything with that information.

**Comment by eaneatfruit** [comment]
I don't think Multirelay has been ported fully to python3 yet.

Current workaround:
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
pip install pycryptodome

**Comment by BuSh1DO** [comment]
> I don't think Multirelay has been ported fully to python3 yet.
> 
> Current workaround:
> curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
> python get-pip.py
> pip install pycryptodome

not work for me...

root@somehost:/opt/Responder-master/tools# pip3 install pycryptodome
Requirement already satisfied: pycryptodome in /usr/local/lib/python3.9/dist-packages (3.9.9)
root@somehost:/opt/Responder-master/tools# pip install pycryptodome
Requirement already satisfied: pycryptodome in /usr/local/lib/python3.9/dist-packages (3.9.9)
root@somehost:/opt/Responder-master/tools# 


root@somehost:/opt/Responder-master/tools# python MultiRelay.py 

Crypto lib is not installed. You won't be able to live dump the hashes.
You can install it on debian based os with this command: apt-get install python-crypto
The Sam file will be saved anyway and you will have the bootkey.

Traceback (most recent call last):
  File "MultiRelay.py", line 39, in <module>
    from MultiRelay.RelayMultiCore import *
  File "/opt/Responder-master/tools/MultiRelay/RelayMultiCore.py", line 31, in <module>
    from framework.win32.hashdump import dump_file_hashes
  File "/opt/Responder-master/tools/MultiRelay/creddump/framework/win32/hashdump.py", line 27, in <module>
    from Crypto.Hash import MD5
ImportError: No module named Crypto.Hash

**Comment by braimee** [comment]
@n8zwn did you ever find a fix/workaround for this?  I've got a brand new Kali build and my Multirelay has the exact same output.  Did a `pip install cryptodome` and still not working.

**Comment by braimee** [comment]
I think I got it working.  I went here (https://pypi.org/project/pycrypto/) and then followed the instructions to download the pycrypto package (https://github.com/pycrypto/pycrypto) and then did:

````
sudo python ./setup.py build
sudo python ./setup.py install
````

MultiRelay appears to be working now!

**Comment by bagels-sec** [comment]
> I think I got it working. I went here (https://pypi.org/project/pycrypto/) and then followed the instructions to download the pycrypto package (https://github.com/pycrypto/pycrypto) and then did:
> 
> ```
> sudo python ./setup.py build
> sudo python ./setup.py install
> ```
> 
> MultiRelay appears to be working now!

+1 Working for me now also after following above steps, cheers @braimee :)

**Comment by braimee** [comment]
Hey just a quick update to this.  With the recent changes made in Multirelay, today the "fix" I posted above didn't seem to work.  I was still getting warned about `crypto lib is not installed.`

Keep in mind that in a case like this I'm very much a "just keep trying stuff and installing things until errors go away" guy, but doing *this* seemed to make Multirelay happy:

`sudo pip3 install pycrypto`

**Comment by lgandx** [comment]
Yes, the new version takes care of that, from now on make sure to install python-pycryptodome as MultiRelay now uses Impacket's SecretsDump.
Eventually, I will either make a dedicated git repo for MultiRelay, or update/create a readme for it.
