### ISSUE TITLE
issue with non-english usernames 

### ISSUE THREAD

**Issue by uvzz** [lgandx/Responder#146]
Hi,

I'm encountering issues with capturing net-ntlm hashes when the user includes non-english characters, in this example - hebrew:

ÓÕÓ Üæ'Ùß::LAPTOP-JLNG5VOO:3494bc1f5f627a15:31B450CA62953534A8B135BC59FEE336:010100000000000014E70A178EC6D601FEFAE93D0269F121000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000002000007E97C5C051B8100FA0D206D7F5B02611FA5BBB7BCCE7437DD50A2C79300B6E300A001000000000000000000000000000000000000900120048005400540050002F0077007000610064000000000000000000

is it a known limitation?

Thanks!

**Comment by lgandx** [comment]
I would need a pcap file to reproduce this.
