### ISSUE TITLE
Feature Request: Add timestamp to all output

### ISSUE THREAD

**Issue by mubix** [lgandx/Responder#15]
It would be nice to have a flag that automatically prefixes all output with a date timestamp:

```
[20161018-03:15:00 -400] - [HTTP] Sending NTLM authentication request to 192.168.1.100
```

**Comment by lgandx** [comment]
Should be in Responder-Session.log no?

**Comment by mubix** [comment]
@lgandx it totally is, sorry I missed, that, would be nice if there was a way to make that in the main output too, but I'm content if you don't want that now that I know where to get it.

**Comment by lgandx** [comment]
No pb! Will check, it could be nice doh.
Cheers
