### ISSUE TITLE
IPv6 support missing

### ISSUE THREAD

**Issue by bert128** [lgandx/Responder#156]
Responder does not support IPv6 at all. In particular:

- None of the credential capture services listen on IPv6 sockets.
- Responder does not join the IPv6 multicast groups for LLMNR or MDNS.
- Responder does not return AAAA addresses in responses.

Modern operating systems will use IPv6 by default. They will perform LLMNR and MDNS lookups using IPv6 first, before falling back to legacy IPv4. This happens over the link-local addresses, even on a legacy network which does not have routable IPv6 connectivity.

This causes Responder to fail entirely on an IPv6-only network.

On a legacy-only network, Responder could sometimes send its answer *before* any legitimate hosts, resulting in a successful attack even against a valid name. Once dual stack hosts are introduced, they will send IPv6 lookup requests first, so a legitimate host may answer the request before it gets resent over legacy IP if both the source and target host are IPv6-reachable.

Hosts may attempt to look up an AAAA record (IPv6 address), if it receives one then it will try to connect to the IPv6 address in preference to any legacy IPv4 address it might have. Since Responder cannot listen on IPv6 sockets nor respond to AAAA lookup requests, this will result in traffic being lost.

A related bug is also present if the system is configured to use IPv6 DNS resolvers:
#152

**Comment by lgandx** [comment]
Hi, 

For now the default behavior is IPv4, when that changes I'll make sure to port everything to IPv6.

Thanks,

**Comment by bert128** [comment]
Default behaviour on any modern OS is to use IPv6 first, LLMNR/MDNS send to the IPv6 multicast address even if no explicit IPv6 routable addresses are configured, and some protocols are IPv6-only (eg windows homegroup, airdrop etc). Support for IPv6 was one of the primary design goals of LLMNR.

Devices can communicate with each other using the IPv6 link-local addresses (fe80::/10) even in the absence of any supporting infrastructure. This actually fits in very well with the intended use of MDNS/LLMNR, which are designed to facilitate name lookups when no managed DNS infrastructure exists.

If an AAAA response is received, it will also be used in preference to any A response. For example:

```
bert@testmbp ~ % telnet flughafen.local
Trying fe80::21b:63ff:fef1:2373...
telnet: connect to address fe80::21b:63ff:fef1:2373: Connection refused
Trying 192.168.200.172...
telnet: connect to address 192.168.200.172: Connection refused
```

Ignoring AAAA requests and not responding to the IPv6 LLMNR/MDNS multicast requests makes the attack significantly less effective on a network with modern hosts present.

Not supporting IPv6 at all renders the tool entirely useless on an IPv6-only network. Some companies have IPv6-only networks, for instance Microsoft and Facebook have documented this publicly.

**Comment by lgandx** [comment]
You're right. I will implement it soon.

Cheers

**Comment by lgandx** [comment]
Hi, 
It took more time that expected, but the update finally came out.
Let me know if the implementation looks like what you were expecting and if you find any bugs/issues.
I'll be closing this issue for now.
Cheers

**Comment by fgeek** [comment]
@lgandx thank you!

**Comment by bert128** [comment]
Excellent thanks! 
I've been off over the xmas/newyear period but i will be giving the updated version a thorough try this week.
