### ISSUE TITLE
SSLKEYLOGFILE Support

### ISSUE THREAD

**Issue by mohemiv** [lgandx/Responder#157]
It will be nice to have the support of the SSLKEYLOGFILE environment variable in order to create an easy method to decrypt incoming TLS/SSL traffic.

**Comment by lgandx** [comment]
You already have the keys in the /certs folder.

**Comment by mohemiv** [comment]
It’s not enough to have the keys you have specified in order to decrypt the
corresponding TLS traffic, because most of the time TLS uses Ephemeral
Diffie-Hellman.
