### ISSUE TITLE
Weird Bug in MultiRelay.py

### ISSUE THREAD

**Issue by hoodsware** [lgandx/Responder#162]
I thought a video will provide a better explanation than expressing with my words.

After following the instructions and running the `responder-MultiRelay` in kali linux that comes preinstalled with watch it till the end that after I exited from `root` to normal user and I've executed again and it tells me I have to re-compile the windows binaries which I already did from the first time?

![MultiRelay](https://media.giphy.com/media/thKqz9IZvL9yBvtgZk/giphy.gif)

**Comment by lgandx** [comment]
Hi, 

I have no idea how MultiRelay is implemented on Kali, and I don't provide support for any distribution adaptation of my tools.

Best is to use you own operating system and install the tools you like yourself.

Cheers

**Comment by hoodsware** [comment]
Actually I just tested again and it works but the only condition is when using `responder-MultiRelay` or `./MultiRelay.py` that it ahs to directly in `/usr/share/responder/tools` folder and it works just fine. Turns out the shortcut is not dynamic after all anyways closing it now.

Cheers
