### ISSUE TITLE
-r, --wredir / -d, --NBTNSdomain functionality is enabled by default?

### ISSUE THREAD

**Issue by ethack** [lgandx/Responder#166]
I believe that the `-w` and `-d` command line options are no-ops and the code, by default, enables these features that claim to be dangerous.

```
  -r, --wredir          Enable answers for netbios wredir suffix queries.
                        Answering to wredir will likely break stuff on the
                        network. Default: Off
  -d, --NBTNSdomain     Enable answers for netbios domain suffix queries.
                        Answering to domain suffixes will likely break stuff
                        on the network. Default: Off
```

These flags set `Wredirect` and `NBTNSDomain` variables here:
https://github.com/lgandx/Responder/blob/3fe574683bd90524ede52b0994e0714e65c4dacc/Responder.py#L36-L37

Those values are transferred to the global settings variable here:
https://github.com/lgandx/Responder/blob/3fe574683bd90524ede52b0994e0714e65c4dacc/settings.py#L181-L182

And finally those settings are used in the `Validate_NBT_NS` function here:
https://github.com/lgandx/Responder/blob/3fe574683bd90524ede52b0994e0714e65c4dacc/poisoners/NBTNS.py#L28-L40

[`ripgrep`](https://github.com/BurntSushi/ripgrep) shows they are not used anywhere else. (`egrep -r 'Wredirect|NBTNSDomain' .` if you prefer)
```
$ rg 'Wredirect|NBTNSDomain'  
settings.py
181:		self.Wredirect          = options.Wredirect
182:		self.NBTNSDomain        = options.NBTNSDomain

Responder.py
36:parser.add_option('-r', '--wredir',        action="store_true", help="Enable answers for netbios wredir suffix queries. Answering to wredir will likely break stuff on the network. Default: False", dest="Wredirect", default=False)
37:parser.add_option('-d', '--NBTNSdomain',   action="store_true", help="Enable answers for netbios domain suffix queries. Answering to domain suffixes will likely break stuff on the network. Default: False", dest="NBTNSDomain", default=False)

poisoners/NBTNS.py
34:	elif settings.Config.NBTNSDomain:
37:	elif settings.Config.Wredirect:
```

But `Validate_NBT_NS` is not used anywhere in the project. It is dead code.
```
$ rg Validate_NBT_NS                       
poisoners/NBTNS.py
28:def Validate_NBT_NS(data):
```

Using `git bisect` I found that this function used to be called [here](https://github.com/lgandx/Responder/blob/f4bd612e083698fd94308fd2fd15ba7d8d289fd8/Responder.py#L405) and [here](https://github.com/lgandx/Responder/blob/f4bd612e083698fd94308fd2fd15ba7d8d289fd8/Responder.py#L453) prior to v2.3.0. `bisect` shows that [this commit](https://github.com/lgandx/Responder/commit/050edc22f35b876a297a9c7a80e43029b955c22d) involving a complete refactor is when the calls to `Validate_NBT_NS` were dropped.

Were the calls to `Validate_NBT_NS` (and thus `-w/-d` flags) dropped on purpose? I think that's only plausible if the protections they offer were either found to be not needed or were made obsolete by other settings (e.g. `DontRespondToName = ISATAP`).

If that's the case, I think the arguments and readme should be updated to remove these as options to avoid confusion. The [current control path](https://github.com/lgandx/Responder/blob/3fe574683bd90524ede52b0994e0714e65c4dacc/poisoners/NBTNS.py#L49-L51) that determines which hosts to poison seems to be [almost entirely dependent](https://github.com/lgandx/Responder/blob/3fe574683bd90524ede52b0994e0714e65c4dacc/utils.py#L94-L117) on the `[Dont]RespondTo[Name]` options in the config file.

If removing the calls to `Validate_NBT_NS` was unintentional or responding to Workstation/Redirect and Domain Controller requests by default is undesirable, then I suggest putting the call back in. I haven't tested this change but I think it would be like this:

```diff
diff --git a/poisoners/NBTNS.py b/poisoners/NBTNS.py
index 5000e81..7708b6a 100644
--- a/poisoners/NBTNS.py
+++ b/poisoners/NBTNS.py
@@ -45,8 +45,10 @@ class NBTNS(BaseRequestHandler):
        def handle(self):
 
                data, socket = self.request
-               Name = Decode_Name(NetworkRecvBufferPython2or3(data[13:45]))
                # Break out if we don't want to respond to this host
+               if not Validate_NBT_NS(data):
+                       return None
+               Name = Decode_Name(NetworkRecvBufferPython2or3(data[13:45]))
                if RespondToThisHost(self.client_address[0], Name) is not True:
                        return None
```

**Comment by lgandx** [comment]
The domain option (-d) was enforced -when Responder was created- out of caution in case it causes disruption on client's networks. Nowadays, it has been proven that it doesn't in most cases.
And you're right,  this should be updated and those options should be removed.
Thank you for your report, i'll make the changes when I have a minute :)
