### ISSUE TITLE
AttributeError: 'module' object has no attribute 'check_output' || ERROR

### ISSUE THREAD

**Issue by YuriMaram** [lgandx/Responder#167]
python Responder.py -i x.x.x.x -I eth0 -PrvF

           NBT-NS, LLMNR & MDNS Responder 2.3.3.6

  Author: Laurent Gaffie (laurent.gaffie@gmail.com)
  To kill this script hit CRTL-C

Traceback (most recent call last):
  File "Responder.py", line 56, in <module>
    settings.Config.populate(options)
  File "/home/test/Responder-2.3.3.9/settings.py", line 234, in populate
    NetworkCard = subprocess.check_output(["ip", "address", "show"])
AttributeError: 'module' object has no attribute 'check_output'

Why isn't it working? And what would be the solution to the problem?

**Comment by fgeek** [comment]
What is your Python version?

**Comment by YuriMaram** [comment]
2.6

**Comment by fgeek** [comment]
That is the reason for your issue. Use more recent version of Python.

**Comment by fgeek** [comment]
Can you try:
```
virtualenv -p python3 responder-env
. ./responder-env/bin/activate
# prompt should say something like (responder-env) foo@bar:~$
git clone https://github.com/lgandx/Responder.git
cd Responder
python3 Responder.py -I eth0
```

**Comment by YuriMaram** [comment]
Thanks for the suggestion to fix the problem
just a question, does version 2.6 work on older versions of Responder?

**Comment by lgandx** [comment]
Hello, 

You should probably update your Responder version, right now it's 3.0.6.0 :)

Thanks,
