### ISSUE TITLE
user not in targetlist

### ISSUE THREAD

**Issue by JK-Love** [lgandx/Responder#174]
![image](https://user-images.githubusercontent.com/63699609/141759610-04cdecf6-26f5-4a1d-a8ea-5b30cd0b0333.png)
![image](https://user-images.githubusercontent.com/63699609/141759401-ef5ae990-f7d3-49dd-8dbe-132e660261dc.png)

192.168.71.150  192.168.71.151
all:username:administartor  pass:123
WORKGROUP
sign:false

192.168.71.151----->kali------>192.168.71.150
Then the error in the picture above appears
I don't know what went wrong

**Comment by lgandx** [comment]
Hello, 
Multirelay is not supported anymore.
Thanks
