### ISSUE TITLE
Python 3.10 deprecations

### ISSUE THREAD

**Issue by noraj** [lgandx/Responder#179]
# Python 3.10 issues

- [ ] https://github.com/lgandx/Responder/issues/172
- [ ] this issue

## Description

Some deprecation warnings are thrown:

```
/usr/share/responder/Responder.py:342: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  thread.setDaemon(True)
/usr/share/responder/Responder.py:235: DeprecationWarning: ssl.wrap_socket() is deprecated, use SSLContext.wrap_socket()
  server.socket = ssl.wrap_socket(server.socket, certfile=cert, keyfile=key, server_side=True)
[!] Error starting SSL server on port 443, check permissions or other servers running.
[!] Error starting SSL server on port 5986, check permissions or other servers running.
```

## References

- https://docs.python.org/3/whatsnew/changelog.html#python-3-10-0-final
- https://docs.python.org/3/whatsnew/3.10.html

**Comment by lgandx** [comment]
Will have to check if that affects the python2 version.
When I built Responder it was made to work on any device, packet parsing and sending was all built from scratch for that reason.
So if you were able to get a shell on a router -for example- that has a minimal python2 installed, it would work.
Will have a look when I have time.

**Comment by r3k2** [comment]
this is a big issue
