### ISSUE TITLE
Help displayed by Responder refers to removed options

### ISSUE THREAD

**Issue by bert128** [lgandx/Responder#186]
When running responder with no options or incorrect options, help is displayed.
The help gives an example which uses the "-f" and "-f" options which no longer exist. Following the example puts you in a loop whereby it complains that the options are incorrect, and recommending you to use the incorrect options:

<img width="354" alt="Screenshot 2022-01-12 at 12 36 25" src="https://user-images.githubusercontent.com/19311342/149067285-7632f266-acc9-4b26-9e59-e356be56b98a.png">

**Comment by lgandx** [comment]
This has been resolved with the latest pull req.

Thank you!
