### ISSUE TITLE
"RespondTo","DontRespondeTo" dont work with ipv4 

### ISSUE THREAD

**Issue by HydroSausager** [lgandx/Responder#187]
Tested on ubuntu and kali.
There is regular 10.11.7.0/24 subnet.

While working, Responder recognizes every IPv4 address with prefix "::ffff:".
Because of this i cant make "RespondTo","DontRespondeTo" in Responder.conf work...

If you use regular IPv4 in Responder.conf, for example - "DontRespondTo=10.11.7.118", Responder will ignore this because "::ffff:10.11.7.118" != "10.11.7.118" 
(using ::ffff:10.11.7.118 in Responder.conf also breakes config)

![изображение](https://user-images.githubusercontent.com/45184745/151511734-0b52e4cd-65f1-44c9-b40b-a99142c89701.png)

![изображение](https://user-images.githubusercontent.com/45184745/151511983-be3c6219-ab2e-41ba-9e00-8439a6540216.png)

![изображение](https://user-images.githubusercontent.com/45184745/151510530-2e322901-e73b-466c-bed3-4ff24251d040.png)

**Comment by corsch** [comment]
IPv6 is also broken in "RespondTo" and "DontRespondeTo".

**Comment by el-dud3rino** [comment]
if i had more time i could come up with something better, but a workaround i created was for ignoring some MDNS names. if you convert the Request_Name to ascii you can see it adds in a \x05 between the hostname and domain .

Put this inside the poisoners/MDNS.py file under the comment for #Break out if we don't want to respond to this host
`               Ignore1 = 'computer1.local'
                Ignore2 = 'computer2.local'
                Ignore3 = 'computer3.local'

                Final = Request_Name.encode("ascii","ignore")
                Final_ascii = Final.decode()
                Final_ascii = re.sub(r'[\x05]+', '', Final_ascii)

                Ignore1 = Ignore1.encode("ascii","ignore")
                Ignore1_ascii = Ignore1.decode()
                Ignore2 = Ignore2.encode("ascii","ignore")
                Ignore2_ascii = Ignore2.decode()
                Ignore3 = Ignore3.encode("ascii","ignore")
                Ignore3_ascii = Ignore3.decode()

                if ((not Request_Name) or (Final_ascii == Ignore3_ascii) or (Final_ascii == Ignore1_ascii) or (Final_ascii == Ignore2_ascii) or (RespondToThisHost(self.client_address[0], Request_Name) is not True)):
                        return None`

**Comment by lgandx** [comment]
Fixed in https://github.com/lgandx/Responder/commit/2765ef4e668bc3493924aae5032e3ec63078ac42

Thanks for submitting this issue
