### ISSUE TITLE
DE-RPC server status not correct

### ISSUE THREAD

**Issue by kitchung** [lgandx/Responder#189]
Line 512 should read:
`	print('    %-27s' % "DCE-RPC server" + (enabled if settings.Config.DCERPC_On_Off else disabled))
`

Instead of:
`	print('    %-27s' % "DCE-RPC server" + (enabled if settings.Config.RDP_On_Off else disabled))
`

**Comment by antifob** [comment]
Appears to be fixed by https://github.com/lgandx/Responder/commit/ee88da1af84680368b7da654297e3f97397dcd2e
Can this be closed?

**Comment by kitchung** [comment]
I'd think so.
