### ISSUE TITLE
[feature request] option to have multirelay execute a  single command  on target box.

### ISSUE THREAD

**Issue by thesle3p** [lgandx/Responder#19]
Any chance you could add  the option to run a single command (stager command,etc) on the target instead of dropping to a shell to multirelay?

**Comment by lgandx** [comment]
What would be the scenario like? I'm not sure to understand why that would be needed, you can execute one command now and type exit to return in relay mode.

**Comment by thesle3p** [comment]
Scripting

**Comment by lgandx** [comment]
Yeah make sense ;)

**Comment by thesle3p** [comment]
Thanks :)

**Comment by lgandx** [comment]
Should MultiRelay exit on completion?

**Comment by thesle3p** [comment]
yes.

**Comment by lgandx** [comment]
Done. 
Use -c (or --command) whoami for example or -d (or --dump) to dump hashes. 
./MultiRelay.py -t 10.10.10.20 -c whoami -d -u ALL

Both can be used at the same time or independently.

**Comment by thesle3p** [comment]
Thanks.
