### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by MexHigh** [lgandx/Responder#192]
First of all, thank you for this awesome tool and the continuing support.

I'm using this tool in a complex toolset and the dependency management became kind of complicated. So I decided to use the requirements.txt to install the dependencies of the other tools I'm using.

Would you mind adding one to the projects root?

**Comment by BustedSec** [comment]
check out github.com/trustedsec/ptf for an alternate way to install responder along with it's required dependencies.

**Comment by lgandx** [comment]
Hi, 
I've added the file, usually Responder works out of the box, but just in case i added it.
Notes: This is for python3 and Responder should always be launched with python3, python2 support is still supported for some specific scenarios (router compromises, Raspberry Pi, etc) but will be dropped at some point.
