### ISSUE TITLE
Keep getting netifaces not installed message

### ISSUE THREAD

**Issue by algowful** [lgandx/Responder#196]
I am runing Debian and I have installed netifaces using `python3 -m pip install netifaces` and `pip install netifaces` as well as running it with python2.7 and I keep getting the same message:

```
You need to install python-netifaces or run Responder with python3...
Try "apt-get install python-netifaces" or "pip install netifaces"
```
I am running it with this command `sudo python3 ./Responder.py` to test.

**Comment by lgandx** [comment]
Try:
python3 Responder.py .....

**Comment by antifob** [comment]
@algowful Could you please close this issue if it's resolved? Thanks
