### ISSUE TITLE
deprecation problems with python 3.10

### ISSUE THREAD

**Issue by RDLL** [lgandx/Responder#197]
![20220420T021224105713575-0500](https://user-images.githubusercontent.com/31356903/164187279-0efcf28d-9400-4b48-bbb8-a1df17e40fe6.png)
Tested on Arch Linux.
Also fixed, making some corrections to responder.py code, based on this [tutorial](https://docs.python.org/3/library/ssl.html).
Since I don't know if it's a general problem, I attach a link to my [fork](https://github.com/RDLL/Responder).

**Comment by valorisa** [comment]
Hello,
I'm using the platform www.hackthebox.com and Responder 3.1.1.0. 
When i try the following command from a console : 

'sudo python3 ./Responder.py -I tun0 --verbose'

 i get : ' /home/valorisa/Responder/./Responder.py:366: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  thread.setDaemon(True)
[!] Error starting SSL server on port 5986, check permissions or other servers running.
[!] Error starting SSL server on port 443, check permissions or other servers running.'

I'm a brand new user of Python. Thanks for your help.
Valorisa

**Comment by RDLL** [comment]
The servers error is normal, but if it doesn't give any response, you can try to kill the httpd service.

**Comment by valorisa** [comment]
Can I try to kill the https service from Responder.conf or an other way?

**Comment by RDLL** [comment]
you can do it from the terminal

`sudo systemctl stop httpd'

**Comment by valorisa** [comment]
Thanks for the information.

**Comment by valorisa** [comment]
I use BlackArch Linux.

**Comment by valorisa** [comment]
All is nice.

**Comment by valorisa** [comment]
Thanks you very much for the _Responder.py_ fixed file because I've been struggling for several days.

**Comment by antifob** [comment]
@valorisa If this issue is resolved, can you close it please? Thanks

**Comment by antifob** [comment]
Note that Python 3.10 issues are already mentionned in #172 and #179

**Comment by lgandx** [comment]
Closing now.
