### ISSUE TITLE
Report.py Broken 

### ISSUE THREAD

**Issue by Zetlin** [lgandx/Responder#198]
When trying to run the report, you are faced with invalid syntax errors. 

Most recent kali linux build, Python 3.9.10

It does work with Python 2.7.18

![image](https://user-images.githubusercontent.com/67925270/164773896-f4cfdd36-7d04-4039-ac96-caeb54ad4995.png)

**Comment by lgandx** [comment]
yep, will push fix soon.

**Comment by lgandx** [comment]
This has been fixed. Closing this issue.
