### ISSUE TITLE
Multirelay SMBv2 support?

### ISSUE THREAD

**Issue by elliot-holley** [lgandx/Responder#200]
hello, and thanks for all the effort you've put into this project :)

i just thought that adding SMBv2 support to Multirelay would be good. if this would be too laborious, the v2 implementation from impacket's ntlmrelayx.py could be used?

many thanks

**Comment by lgandx** [comment]
Hi, 
MultiRelay is not supported anymore, I suggest using any up to date NTLM relay tools.

Thanks,
