### ISSUE TITLE
Oracle Linux/Responder Unable to starting Server

### ISSUE THREAD

**Issue by BustedSec** [lgandx/Responder#201]
After installing Responder and the pip3 dependency for netifaces I get the following error when running Responder.py -I eth0 
 [+] Listening for events...

[!] Error starting TCP server on port 135, check permissions or other servers running.
[!] Error starting UDP server on port 137, check permissions or other servers running.
[!] Error starting SSL server on port 5986, check permissions or other servers running.
[!] Error starting TCP server on port 80, check permissions or other servers running.
[!] Error starting SSL server on port 443, check permissions or other servers running.
[!] Error starting UDP server on port 5355, check permissions or other servers running.
[!] Error starting UDP server on port 88, check permissions or other servers running.
[!] Error starting TCP server on port 5985, check permissions or other servers running.
[!] Error starting UDP server on port 5353, check permissions or other servers running.
[!] Error starting TCP server on port 48442, check permissions or other servers running.
[!] Error starting TCP server on port 3389, check permissions or other servers running.
[!] Error starting UDP server on port 138, check permissions or other servers running.
[!] Error starting TCP server on port 21, check permissions or other servers running.
[!] Error starting TCP server on port 88, check permissions or other servers running.
[!] Error starting UDP server on port 1434, check permissions or other servers running.
[!] Error starting TCP server on port 445, check permissions or other servers running.
[!] Error starting TCP server on port 139, check permissions or other servers running.
[!] Error starting TCP server on port 110, check permissions or other servers running.
[!] Error starting TCP server on port 389, check permissions or other servers running.
[!] Error starting TCP server on port 1433, check permissions or other servers running.
[!] Error starting TCP server on port 25, check permissions or other servers running.
[!] Error starting TCP server on port 143, check permissions or other servers running.
[!] Error starting UDP server on port 389, check permissions or other servers running.
[!] Error starting TCP server on port 53, check permissions or other servers running.
[!] Error starting TCP server on port 587, check permissions or other servers running.
[!] Error starting UDP server on port 53, check permissions or other servers running.

I've done a lot of troubleshooting. I believe it's likely related to the netifaces package but unable to tell. Is there anyway to bypass this error? I am able to use netcat to start listeners on the above ports so I know they are able to be opened.

**Comment by aledanugf** [comment]
Hi. Got the same issue while having disabled ipv6 with "ipv6.disable=1" in grub. After removing ipv6.disable=1 and rebooting, responder worked fine again.

**Comment by BustedSec** [comment]
> Hi. Got the same issue while having disabled ipv6 with "ipv6.disable=1" in grub. After removing ipv6.disable=1 and rebooting, responder worked fine again.

Thank you so much for this. I will make the edit, reboot, and see if that fixes it later today. Then I'll update my issue.

**Comment by BustedSec** [comment]
So yes, the issue was that IPv6 was not enabled. I followed some guides for my OS and figured out how to enable it and it works fine now. I had to edit a few files, not just /etc/default/grub, needed to append to /etc/sysctl.conf with 
#enable ipv6
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0
net.ipv6.conf.eth0.disable_ipv6 = 0

These  resources were useful
https://www.cyberithub.com/how-to-enable-ipv6-on-centos-rhel-7/
https://www.thegeekdiary.com/how-to-enable-ipv6-in-centos-rhel-8/
https://askubuntu.com/questions/41543/how-to-dynamically-enable-and-disable-ipv6-on-an-interface

**Comment by antifob** [comment]
@BustedSec Is this issue resolved?
