### ISSUE TITLE
DHCP options do not work on macOS

### ISSUE THREAD

**Issue by bismark-foofus** [lgandx/Responder#204]
The latest versions of Responder with the DHCP code do not work on macOS or other BSD based systems.  BSD based systems do not support AF_PACKET or PF_PACKET used [here](https://github.com/lgandx/Responder/blob/983a1c6576cb7dfe6cabea93e56dc4f2c557621b/poisoners/DHCP.py#L339) in the DHCP poisoner code.  

Scapy's [BSD supersocket code](https://github.com/secdev/scapy/blob/master/scapy/arch/bpf/supersocket.py) might be of use. 

I'm a python hack so trying to make something work but haven't yet.

**Comment by lgandx** [comment]
Unfortunately Osx is not supported anymore, best way to run Responder would be with a linux VM in VMware fusion, configured in bridge mode.
