### ISSUE TITLE
Error starting several servers despite ports being free

### ISSUE THREAD

**Issue by askenderski** [lgandx/Responder#205]
When I run the command `sudo responder -i <ip of target> -I ALL -v`, I get the following errors:

```
Error starting UDP server on port 5355, check permissions or other servers running.
Error starting UDP server on port 5353, check permissions or other servers running.
Error starting SSL server on port 5986, check permissions or other servers running.
Error starting SSL server on port 443, check permissions or other servers running.
```

At first it was just the 5355 error, I tried checking for services running on those ports in many ways and none were there. I tried updating responder and then the other 3 errors appeared. I tried not using sudo, but nothing changed. I tried restarting my device and doing a full upgrade with apt, using specific interfaces with the ip and without the ip, but I just can't figure out the issue. I see no reason for a lack of permissions and the ports are not being used. What could be the reason, is it something I'm misunderstanding or is this a bug?

**Comment by cheesemonkey00** [comment]
Same issues with mine, port 53/389.  I've done updates/upgrades, messed with resolv, ldap and still having issues with it.  
No processes are running on the ports, so  I can't kill anything.  Running as sudo.

**Comment by BustedSec** [comment]
do you have ipv6 enabled?

**Comment by cheesemonkey00** [comment]
Thank you!
I ended up rebooting a few times, and it worked without an issue.  I'm not sure what fixed it honestly.  If it happens again and I fix it without a reboot I'll update it for others.

**Comment by lgandx** [comment]
Closing this issue
