### ISSUE TITLE
Outdated version number string

### ISSUE THREAD

**Issue by Flnch** [lgandx/Responder#207]
Hi, via CLI arguments one can check/print the version of responder. Apparently, the current version string is set to `__version__ = 'Responder 3.1.1.0'` ([see latest release tag](https://github.com/lgandx/Responder/blob/v3.1.2.0/settings.py#L26)) while the release version is already at `3.1.2.0`.

This is no critical problem, but I was confused as the CLI version output did not match the Debian package version :)

**Comment by lgandx** [comment]
Resolved in the latest version. 
Thanks for submitting this issue.
