### ISSUE TITLE
"DontRespondToName=" doesn't work/stop Responder from responding to queries

### ISSUE THREAD

**Issue by el-dud3rino** [lgandx/Responder#208]
No matter the name entered in "DoneRespondToName=" portion in responder.conf, it will still respond to MDNS names.

if i had more time i could come up with something better, but a workaround i created was for ignoring some MDNS names. if you convert the Request_Name to ascii you can see it adds in a \x05 between the hostname and domain . after the below is added to MDNS.py, you can add hostnames to the .conf file like normal

I put this inside the poisoners/MDNS.py file under the comment for #Break out if we don't want to respond to this host
```
                Final = Request_Name.encode("ascii","ignore")
                Final_ascii = Final.decode()
                Final_ascii = re.sub(r'[\x05]+', '', Final_ascii)

                if ((not Request_Name) or (RespondToThisHost(self.client_address[0], Final_ascii) is not True)):
                        return None
```

I've since found a potentially better fix for this as i noticed some MDNS names having a \x04 in front. if you change the beginning length of 2 instead of 1 on Line 33, seems to drop off the hex values that cause issues, have not tested this extensively yet though, just know that if it change that value, i can add names to .conf and it won't respond to them 

```
Name_ = data[2+NameLen:1+NameLen+NameLen_+1]
```

**Comment by lgandx** [comment]
This issue has been fixed in https://github.com/lgandx/Responder/commit/0bc226b4beaa84eb3ac26f5d563959ccf567262b

'.local' tld was automatically added to all provided name in the DontRespondToName list and the \x05 character was removed during comparison. 

Thanks for submitting this issue.
