### ISSUE TITLE
Errors Starting Port 443, and 25

### ISSUE THREAD

**Issue by Gophishtesting** [lgandx/Responder#212]
[!] Error starting SSL server on port 443, check permissions or other servers running.
[!] Error starting TCP server on port 25, check permissions or other servers running.

Running on amazon Linux 2

**Comment by lgandx** [comment]
Hello, 
You must have a service running on those ports.
Running the command "netstat -pna|more" as root will show which service is running on those ports.

**Comment by BustedSec** [comment]
I generally use netstat -tulpn | grep :139 to find what is on port 139 for instance, I like your way as well.

**Comment by gmassawe** [comment]
> Hello, You must have a service running on those ports. Running the command "netstat -pna|more" as root will show which service is running on those ports.

I have same problem except the second port is 5986. And yes no services running on port 443 or 5986.

**Comment by Dramelac** [comment]
Same error on Responder 3.1.3.0:
![image](https://user-images.githubusercontent.com/10145128/190594587-1b790ea0-3a50-430e-9a25-98a3f795603e.png)

**Comment by lgandx** [comment]
That looks like a certificate issue.

The OS seems to be Kali, best would be to submit an issue to their repo, as
they adapted responder for their needs.

While this issue is resolved on Kali's end, you can install Responder from
source and run it with no problem:

git clone https://github.com/lgandx/Responder.git && cd Responder

**Comment by Dramelac** [comment]
Indeed, it worked, thank you very much :)

**Comment by BustedSec** [comment]
Tested the above on an older version of Kali I had in a VM that had the same issue, it did indeed fix it. Good job troubleshooting [twosevenzero](https://github.com/twosevenzero)
