### ISSUE TITLE
Monero Donation

### ISSUE THREAD

**Issue by ACK-J** [lgandx/Responder#226]
I use responder a lot and would like to donate some monero to the project. Do you have a public wallet?

**Comment by lgandx** [comment]
Hi,

You can use this monero address for donations:


45reTAK9nYMj1uhTAEUmMX2AzWjntA5vke9zdsn2R9GEMifkhrVyYH5gKZiMWLCK8y5pVmUKXxVvMXo7w6Q7b5iLJNntqpQ


Thank you for supporting this tool!

**Comment by ACK-J** [comment]
sent

**Comment by lgandx** [comment]
Thank you for supporting this project. I appreciate it

**Comment by fgeek** [comment]
Get a room you two! ;)
