### ISSUE TITLE
'Please install python-sqlite3 extension'

### ISSUE THREAD

**Issue by quintoorschot** [lgandx/Responder#227]
Please correct me if I'm wrong, but I am working on Kali Linux and upon running Responser I keep getting an error message stating 'Please install python-sqlite3 extension'. Even though I have clearly installed the extension. Is this an error on my side or in the program itself?

**Comment by also-here** [comment]
Hi quintoorschot,

I don't have a quick answer for you but could you provide some more details. Maybe the output of  `locate sqlite3 |grep python` ? I'm wondering if it's possible you have sqlite3 for one version of python but not necessarily the version you use to run Responder. Also, if you could, just drop into a `python3` and run `import sqlite3` just so we can see what, if any error message it spits out.

**Comment by lgandx** [comment]
Closing this issue since no answer was provided.

**Comment by walterfemiano** [comment]
Had the same issue. By opening python CLI and typing `import sqlite3` I got this error
```
Python 3.12.5 (main, Oct 10 2024, 00:06:23) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kali/.pyenv/versions/3.12.5/lib/python3.12/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/home/kali/.pyenv/versions/3.12.5/lib/python3.12/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
>>> 
```
even if sqlite3 seemed to be installed: `/home/kali/.pyenv/versions/3.12.5/lib/python3.12/sqlite3`.

I managed to solve the issue by changing the python environment from `.pyenv` to `system`

```
└─$ pyenv versions
* system
  3.12.5 (set by /home/kali/.pyenv/version)
```

Hope this helps if anyone else runs into the same problem.
