### ISSUE TITLE
i cant start 12 tcp and 1 ssl servers help

### ISSUE THREAD

**Issue by Flagged-Sys** [lgandx/Responder#229]
[!] Error starting TCP server on port 80, check permissions or other servers running.
[!] Error starting TCP server on port 445, check permissions or other servers running.
[!] Error starting TCP server on port 139, check permissions or other servers running.
[!] Error starting TCP server on port 88, check permissions or other servers running.
[!] Error starting TCP server on port 1433, check permissions or other servers running.
[!] Error starting TCP server on port 21, check permissions or other servers running.
[!] Error starting TCP server on port 110, check permissions or other servers running.
[!] Error starting TCP server on port 389, check permissions or other servers running.
[!] Error starting TCP server on port 587, check permissions or other servers running.
[!] Error starting TCP server on port 25, check permissions or other servers running.
[!] Error starting TCP server on port 143, check permissions or other servers running.
[!] Error starting TCP server on port 53, check permissions or other servers running.
[!] Error starting SSL server on port 443, check permissions or other servers running.

Anybody Know a fix

**Comment by jvgassel** [comment]
Did you start responder as sudo?

**Comment by lgandx** [comment]
Closing issue.
