### ISSUE TITLE
Syntax for "QuickCreds" ("BashBunny") using Responder 

### ISSUE THREAD

**Issue by InfiniteBSOD** [lgandx/Responder#235]
Hello,

Sorry since this is not an issue with Responder "per-se" but hopefully I can get an answer here anyway.

I tried using the latest version of Responder (3.1.3.0) w. the "QuickCreds"-payload for BashBunny:
https://github.com/hak5/bashbunny-payloads/blob/master/payloads/library/credentials/QuickCreds/payload.txt#L20

Row 20 in that payload (see above) specifies the parameters for "Responder" as:
`-w -r -d -P`

On the 18th of May the option to specify "-r" seems to have been removed:
https://github.com/lgandx/Responder/commit/03fa9a7187c80586629c58a297d0d78f2f8da559

I tried editing the "QuickCreds"-payload to only use:
`-w -d -P`
which enables:
```
-w, --wpad            Start the WPAD rogue proxy server. Default value is False
-d, --DHCP            Enable answers for DHCP broadcast requests. This option will inject a WPAD server in the DHCP response. Default: False
-P, --ProxyAuth       Force NTLM (transparently)/Basic (prompt) authentication for the proxy. WPAD doesn't need to be ON. Default: False
```

However trying to execute Responder manually through:
`python Responder.py -I usb0 -w -d -P -v`
returns:
```
[!] Error starting SSL server on port 5986, check permissions or other servers running.
[!] Error starting SSL server on port 443, check permissions or other servers running.
```
checking ports:
```
netstat -lnpt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      430/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      430/sshd
```

I've read the possible solutions:
1) Make sure IPv6 is enabled;
https://github.com/lgandx/Responder/issues/215#issuecomment-1274246261
2) Make sure certs are generated;
https://github.com/lgandx/Responder/issues/212#issuecomment-1304063358

I'll go ahead and test these solutions tomorrow (sadly the BashBunny is not with me atm) but are there any other possible causes "straight of the bat" that people can spot?

The BashBunny (MK II) is running Debian 8 - "Jessie" - on arm and I've built Python 3.11.2 with OpenSSL 3.1.0.

Best Regards

**Comment by also-here** [comment]
Hey Infinite, 
Don't know if you have a chance to test this out yet but it's almost certainly due to the missing certs as noted in #212. The payload looks like it calls Responder from within its directory so it's a bit odd that it's not creating the certs automatically but, in some fashion, they need to be there for the SSL servers to start up.

**Comment by InfiniteBSOD** [comment]
> Hey Infinite, Don't know if you have a chance to test this out yet but it's almost certainly due to the missing certs as noted in #212. The payload looks like it calls Responder from within its directory so it's a bit odd that it's not creating the certs automatically but, in some fashion, they need to be there for the SSL servers to start up.

Thank you for the reply.

I haven't gotten around to test it yet since the BB is with colleagues, the reason (?) why the certs aren't automatically created might be because I manually compiled OpenSSL and Python3?
The original OpenSSL is still installed (I followed these [instructions ](https://docs.python.org/3.11/using/unix.html#custom-openssl)) and Responder might default to the pre-installed OpenSSL which is in.... "/usr/local/ssl"?

Anyway I'll try and report back when I have it (the BB) :)

**Comment by lgandx** [comment]
this issue should be resolved with the latest merge.
Closing now.

**Comment by Terraphice** [comment]
Seems like this wasn't actually fixed with whatever merge that was, either that or it's been broken again since.

I have the exact same setup as Infinite, as we followed the same instructions and docs (from the Hak5 forum) on the same Debian 8 device. I think the only difference is that my Python version is 3.7.9 rather than 3.11.2.

I have the same errors they do, and generating certs doesn't seem to fix them.
