### ISSUE TITLE
about MultiRelay and SMBRelayX

### ISSUE THREAD

**Issue by darkr4y** [lgandx/Responder#24]
I set up a lab about:
inventory pc: win10 172.24.20.65
middle: kali 172.24.20.81
target: win2008r2 172.24.20.57

workgroup enviroment.

I used responder to poison inventory pc, and relay to target by middle.

1. use MultiRelay will return a logon_failure
![image](https://cloud.githubusercontent.com/assets/4407382/21515078/85ceb020-cd07-11e6-92be-ad865247107b.png)

2. use SMBRelayX will return access_denied, I know this error cuz target has UAC on.
![image](https://cloud.githubusercontent.com/assets/4407382/21515118/cb434756-cd07-11e6-9902-8a9c3934aa58.png)

Why use the same environment, two tools returned to the different results?

**Comment by lgandx** [comment]
I'm not sure, best would be to provide a pcap file.

Thanks for the report!

**Comment by darkr4y** [comment]
OK, Wait a minute ..

**Comment by lgandx** [comment]
Minute elapsed, closing this issue :)
