### ISSUE TITLE
regular subnet

### ISSUE THREAD

**Issue by sec13b** [lgandx/Responder#240]
I try use Responder in kali image 
the eth0 is 10.156.156.128

There is 2 regular  subnet.
192.168.88.0/24
192.168.112.0/24

sudo python Responder.py -I eth0 -wF -v

![image](https://github.com/lgandx/Responder/assets/123419537/18d16a16-8023-471e-9606-d626cf22e925)

dont show nothing
How i can do the responder scope for the 2 regular  subnet  (Whitelist scope of IP addresses to interact with) and a responder blacklist (Blacklist of IP addresses not to interact with) 

`─$ sudo python Responder.py -I eth0 -wF -v     

[+] Poisoners:
    LLMNR                      [ON]
    NBT-NS                     [ON]
    MDNS                       [ON]
    DNS                        [ON]
    DHCP                       [OFF]

[+] Servers:
    HTTP server                [ON]
    HTTPS server               [ON]
    WPAD proxy                 [ON]
    Auth proxy                 [OFF]
    SMB server                 [ON]
    Kerberos server            [ON]
    SQL server                 [ON]
    FTP server                 [ON]
    IMAP server                [ON]
    POP3 server                [ON]
    SMTP server                [ON]
    DNS server                 [ON]
    LDAP server                [ON]
    RDP server                 [ON]
    DCE-RPC server             [ON]
    WinRM server               [ON]

[+] HTTP Options:
    Always serving EXE         [OFF]
    Serving EXE                [OFF]
    Serving HTML               [OFF]
    Upstream Proxy             [OFF]

[+] Poisoning Options:
    Analyze Mode               [OFF]
    Force WPAD auth            [ON]
    Force Basic Auth           [OFF]
    Force LM downgrade         [OFF]
    Force ESS downgrade        [OFF]

[+] Generic Options:
    Responder NIC              [eth0]
    Responder IP               [10.156.156.128]
    Responder IPv6             [fe80::5fae:d7ef:c973:5710]
    Challenge set              [1122334455667788]
    Don't Respond To Names     ['ISATAP']

[+] Current Session Variables:
    Responder Machine Name     [WIN-EAG2KZSRLJ6]
    Responder Domain Name      [G6EK.LOCAL]
    Responder DCE-RPC Port     [45460]

[+] Listening for events...`

**Comment by lgandx** [comment]
Hi, 

You can try with "-I ALL" which will listen on all interfaces. You will need to provide an IP to "-i" to specify which IP of all the available interfaces we should poison requests with.
