### ISSUE TITLE
AttributeError: module 'os' has no attribute 'geteuid'. Did you mean: 'getpid'?

### ISSUE THREAD

**Issue by EMU-TIME** [lgandx/Responder#241]
I heard that there are two OS modules that can cause this conflict. 
How can I use an OS module with the geteuid() function?

**Comment by lgandx** [comment]
How is this related to Responder?

**Comment by Criptc** [comment]
I'm guessing that @EMU-TIME tried to run it on Windows, which would cause that error

**Comment by Reelix** [comment]
The full error

```
Traceback (most recent call last):
  File "C:\Utils\Responder\Responder.py", line 50, in <module>
    if not os.geteuid() == 0:
           ^^^^^^^^^^
AttributeError: module 'os' has no attribute 'geteuid'. Did you mean: 'getpid'?```

**Comment by EMU-TIME** [comment]
> I'm guessing that @EMU-TIME tried to run it on Windows, which would cause that error

Yes

**Comment by Reelix** [comment]
If you try and attempt to resolve this manually, you receive many further issues
```
settings.py", line 323, in populate
    NetworkCard = subprocess.check_output(["ifconfig", "-a"])
 ```

```
settings.py", line 326, in populate
    NetworkCard = subprocess.check_output(["ip", "address", "show"])
```
It seems that responder was coded with Unix specific commands in mind, and was not intended to be cross-platform.

**Comment by lgandx** [comment]
closing.
