### ISSUE TITLE
netifaces version

### ISSUE THREAD

**Issue by darkpyrro** [lgandx/Responder#242]
Not an issue really, but are there specific reasons to why Responder requires version 0.10.4 of netifaces, and nothing else?

**Comment by lgandx** [comment]
Responder should work with any version of netifaces.

**Comment by darkpyrro** [comment]
OK, I just wanted to get that verified in the case of needing to troubleshoot things. The reason to the question is that it's specified as "netifaces==0.10.4" in the requirements.txt file.
