### ISSUE TITLE
Responder only catching direct IP invocation requests

### ISSUE THREAD

**Issue by njmulsqb** [lgandx/Responder#246]
Hi,

I am pentesting an AD environment hosted on Azure (not Azure AD or AAD DS but just AD DS hosted on Azure) and upon running Responder for LLMNR poisoning, I can only catch the hashes if the other VM in the network types `\\192.168.10.1` (attacker machine's IP) directly into the file explorer. It does nothing and catches nothing if victim enters any other string like `\\IDontKnow`

Why is it so? Is responder failing to proper catch all the LLMNR requests?

Here's the responder command I am using
```
sudo responder -I eth0 -dwPv
```
Version: 3.1.3.0

**Comment by njmulsqb** [comment]
![image](https://github.com/lgandx/Responder/assets/47940898/857d4fe5-a4e9-455f-aa00-da29f25b2c8b)
Why is LLMNR and NBT-NS off here? LLMNR is enabled on the VMs here so not the case of LLMNR disabled by GPO

**Comment by njmulsqb** [comment]
![image](https://github.com/lgandx/Responder/assets/47940898/038c596f-6091-4a27-b57d-c9536511b344)
GPO screenshot

**Comment by lgandx** [comment]
Could you please post a picture of launching responder, especially the bottom part.

It looks like LLMNR, MDNS, and NetBIOS ports are in currently in use on your workstation.

**Comment by lgandx** [comment]
closing now.
