### ISSUE TITLE
How to change default port on Responder ?

### ISSUE THREAD

**Issue by fsoc106** [lgandx/Responder#260]
Hello, How to change the listener port of Responder please ? I want listen for SMB the port 4545 instead of 445, is it possible ?
Thanks for you help

**Comment by lgandx** [comment]
Common SMB clients don't provide a port option, SMB is always 139/445.
If you want to do it anyways, you can always edit Responder.py line 328:
threads.append(Thread(target=serve_thread_tcp, args=(settings.Config.Bind_To, 445, SMB1,)))
and change 445 to whatever port you'd like.

Cheers,
