### ISSUE TITLE
Feature Request: LDAP over TLS / LDAPS Support

### ISSUE THREAD

**Issue by MichaelGrafnetter** [lgandx/Responder#263]
Hi, it would be nice if LDAPS was also supported.

Adding the following line to `Responder.py` seems to do the job:

```python
threads.append(Thread(target=serve_thread_SSL, args=(settings.Config.Bind_To, 636, LDAP,)))
```

**Comment by exploide** [comment]
Good idea, also thought about this some weeks ago. I tested your suggestion and it works.

Submitted a PR in #264.
