### ISSUE TITLE
SMBv2 Server Able to be Fingerprinted via GUID

### ISSUE THREAD

**Issue by agreenbhm** [lgandx/Responder#266]
In packets.py, [the "SMB2NegoAns" class has a field "Guid"](https://github.com/lgandx/Responder/blob/4ea3d7b76554dee5160aaf76a0235074590284f8/packets.py#L1699) that is set to a static value.  This value has been identified and published for blue teams to use for fingerprinting with detection tools.  See post here: https://infosec.exchange/@taylorparizo/111689732675331393

Conversely, [the same field for the class "SMBNegoAns"](https://github.com/lgandx/Responder/blob/4ea3d7b76554dee5160aaf76a0235074590284f8/packets.py#L1341) (which I assume is for SMBv1) dynamically generates this GUID from urandom at runtime.  Unless there is an explicit reason as to why this field for SMB2 must remain static, it should be dynamically generated at runtime as well.

**Comment by lgandx** [comment]
Great catch!
Working on this and other stuff :)

**Comment by lgandx** [comment]
Solved in https://github.com/lgandx/Responder/commit/66ee7f8f08f57926f5b3694ffb9e87619eee576f and much more potential sig.
Thanks!
