### ISSUE TITLE
Any way to bind to virtual interfaces ? eg: eth0:0

### ISSUE THREAD

**Issue by iNilo** [lgandx/Responder#27]
Any way to bind to virtual interfaces ? eg: eth0:0

**Comment by GGGunrunner** [comment]
I would upvote this request! Same problem:

root@# netstat -nlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:88              0.0.0.0:*               LISTEN      32496/python    
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      32496/python    
tcp        0      0 0.0.0.0:1433            0.0.0.0:*               LISTEN      32496/python    
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      32496/python    
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      32496/python    
tcp        0      0 0.0.0.0:389             0.0.0.0:*               LISTEN      32496/python    
tcp        0      0 0.0.0.0:587             0.0.0.0:*               LISTEN      32496/python    
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      32496/python    
tcp        0      0 0.0.0.0:110             0.0.0.0:*               LISTEN      32496/python    
tcp        0      0 0.0.0.0:143             0.0.0.0:*               LISTEN      32496/python    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      32496/python  

Nmap scan report for  (195.365.42.286)
Host is up (0.0000090s latency).
Not shown: 999 closed ports
PORT   STATE SERVICE
22/tcp open  ssh

Not listening... :(

**Comment by lgandx** [comment]
Last time I checked it was successfully working. If that persist, please resubmit :)
