### ISSUE TITLE
Help filtering Responder "spam?"

### ISSUE THREAD

**Issue by 7MinSec** [lgandx/Responder#284]
Hello,

Something weird I've never seen on a test before: I start Responder-ing like normal with `responder.py -I eth0 -Pv` and then several devices on the network end up Responder-spamming me with hundreds of request like this:

```
[*] [MDNS] Poisoned answer sent to 192.168.11.20   for name SONY-TV(1)._dosvc
...
...
[*] [MDNS] Poisoned answer sent to 192.168.11.20   for name SONY-TV(385)._dosvc
[*] [MDNS] Poisoned answer sent to 192.168.11.20   for name SONY-TV(386)._dosvc
[*] [MDNS] Poisoned answer sent to 192.168.11.20   for name SONY-TV(387)._dosvc
```

Within a few seconds the console log is overwhelmed, errors start popping up, and I have to kill the process.

I've tried playing with the Responder.conf file to see if there's something I can set in the "don't respond to" sections, but I can't get things quieted down.  Any ideas?

Thanks,
Brian

**Comment by griffr10** [comment]
We are seeing the same issue on our current test. It causes Responder to crash within minutes.

**Comment by lgandx** [comment]
Could you provide the stack trace?

Thanks,

**Comment by griffr10** [comment]
Command:
`sudo python3 Responder.py -I eth0 --lm --disable-ess`
Stack Trace:
`----------------------------------------
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/kali/Tools/Responder/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/kali/Tools/Responder/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
  File "/home/kali/Tools/Responder/poisoners/MDNS.py", line 103, in handle
    SavePoisonersToDb({
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/kali/Tools/Responder/poisoners/MDNS.py", line 85, in handle
    SavePoisonersToDb({
  File "/home/kali/Tools/Responder/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
  File "/home/kali/Tools/Responder/utils.py", line 406, in SavePoisonersToDb
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
sqlite3.OperationalError: database is locked
sqlite3.OperationalError: database is locked`

I believe the issue may be occurring because it responder repeatedly trying to poison the same IP and name combination and it is filling up the database.
```[*] [MDNS] Poisoned answer sent to fe80::59b4:f827:4e14:2034 for name FLEX-GRINNELL-CART1(4037)._dosvc[*] [MDNS] Poisoned answer sent to 10.11.20.135    for name FLEX-GRINNELL-CART1(4038)._dosvc          [*] [MDNS] Poisoned answer sent to 10.11.20.135    for name FLEX-GRINNELL-CART1(4039)._dosvc          [*] [MDNS] Poisoned answer sent to 10.11.20.135    for name FLEX-GRINNELL-CART1(4040)._dosvc          [*] [MDNS] Poisoned answer sent to 10.11.20.135    for name FLEX-GRINNELL-CART1(4041)._dosvc          [*] [MDNS] Poisoned answer sent to 10.11.20.135    for name FLEX-GRINNELL-CART1(4042)._dosvc          [*] [MDNS] Poisoned answer sent to 10.11.20.135    for name FLEX-GRINNELL-CART1(4043)._dosvc          [*] [MDNS] Poisoned answer sent to 10.11.20.135    for name FLEX-GRINNELL-CART1(4044)._dosvc          [*] [MDNS] Poisoned answer sent to 10.11.20.135    for name FLEX-GRINNELL-CART1(4045)._dosvc          [*] [MDNS] Poisoned answer sent to 10.11.20.135    for name FLEX-GRINNELL-CART1(4046)._dosvc          [*] [MDNS] Poisoned answer sent to 10.11.20.135    for name FLEX-GRINNELL-CART1(4047)._dosvc          [*] [MDNS] Poisoned answer sent to fe80::59b4:f827:4e14:2034 for name FLEX-GRINNELL-CART1(4047)._dosvc[*] [MDNS] Poisoned answer sent to 10.11.20.135    for name FLEX-GRINNELL-CART1(4049)._dosvc          ----------------------------------------                                                              Exception occurred during processing of request from ('::ffff:10.11.20.135', 5353, 0, 0)              ----------------------------------------                                                              [*] [MDNS] Poisoned answer sent to 10.11.20.135    for name FLEX-GRINNELL-CART1(4050)._dosvc          [*] [MDNS] Poisoned answer sent to fe80::59b4:f827:4e14:2034 for name FLEX-GRINNELL-CART1(4050)._dosvc```

**Comment by 7MinSec** [comment]
And not sure this is helpful but I eventually got this "fixed" on my pentest by setting Responder to not respond to about half a dozen IPv4/IPv6 addresses.  I can do some unblocking of addresses later in this engagement if you need me to do some testing or data-gathering, but right now I need Responder working :-)

**Comment by 7MinSec** [comment]
Just started a new test today and was having the same issue.  I killed Python process and reviewed logs and found tons of entries like this:

```
Poisoned answer sent to "CLIENT_SYSTEM_IPV6_ADDRESS for name "MY-PENTEST-BOX-NAME(4508)._dosvc
[*] [MDNS] Poisoned answer sent to CLIENT_SYSTEM_IPV4_ADDRESS for name MY-PENTEST-BOX-NAME(4509)._dosvc
```
The number in parentheses goes up with each "hit."  I added both the IPv4 and IPv6 addresses do `dontrespondto` and that quieted things down to where I could run the tool without it crashing.

**Comment by 3ldidi94** [comment]
Same issue here. I also need to add IPv4 addresses in the `DontRespondTo` setting to avoid this issue but the tool become less interesting with that setting

**Comment by mattysmith00** [comment]
I've been having the same issue for the past few weeks. 
I have tested it on older versions of Kali from 2022 - 2024, still had the same issue, so switched from Virtualbox to VMware. Issue still remained.

**Comment by jeffmcjunkin** [comment]
I had the same in an isolated environment with a Windows 11 23H2 host being the box looping in responses.

**Comment by puzzlepeaches** [comment]
Cheaty fix that I'm too lazy to create an MR for below:

1. Open `poisoners/MDNS.py`
2. Go to the class definition of MDNS
3. Underneath `MDNSType = Parse_IPV6_Addr(data)` add the following

```python
if b"_dosvc" in data:
    return
```

**Comment by Blissx00** [comment]
> Cheaty fix that I'm too lazy to create an MR for below:
> 
> 1. Open `poisoners/MDNS.py`
> 2. Go to the class definition of MDNS
> 3. Underneath `MDNSType = Parse_IPV6_Addr(data)` add the following
> 
> ```python
> if b"_dosvc" in data:
>     return
> ```

It does work, but it breaks the responder again when you're trying to do SMB relay attack with http and smb turned off.
It won't let the victim machine connect back to the attacker.

How do we fix that ?

**Comment by g0hm4** [comment]
> Cheaty fix that I'm too lazy to create an MR for below:
> 
> 1. Open `poisoners/MDNS.py`
> 2. Go to the class definition of MDNS
> 3. Underneath `MDNSType = Parse_IPV6_Addr(data)` add the following
> 
> ```python
> if b"_dosvc" in data:
>     return
> ```

Works beautifully - thank you

**Comment by jeffmcjunkin** [comment]
I made a PR for @g0hm4 , @7MinSec , and myself with @g0hm4 's fix above. 

@lgandx , is this worth committing for now?

**Comment by lgandx** [comment]
Working on a fix, will push it soon.

**Comment by lgandx** [comment]
Added a permanent fix with: https://github.com/lgandx/Responder/commit/e918fe01c617e482d8b24525db581c403104ab28

You can now disable a TLD for MDNS requests in Responder.conf with the option "DontRespondToTLD", _dosvc is now disable by default.

Thanks for reporting this issue!
