### ISSUE TITLE
Does responder ignore certain types of traffic? 

### ISSUE THREAD

**Issue by ZerkerEOD** [lgandx/Responder#286]
I tried running responder on my network, using the Analysis mode and verbose, and after a few minutes it wasn't detecting any traffic. I then looked at Wireshark and was seeing mDNS and LLMNR traffic, mainly for stuff like Spotify, Google and Microsoft. Does responder ignore specific types of traffic or is my install bunked? I installed through Black Arch repo on EndeavorOS. I needed to install netifaces through pip as an addition to get the tool running but there were no errors when running.

**Comment by lgandx** [comment]
You need to provide the network interface you want Responder to listen on with the -I switch.

**Comment by ZerkerEOD** [comment]
@lgandx, sorry the -I switch was used.
