### ISSUE TITLE
Python3 Support?

### ISSUE THREAD

**Issue by servebeer** [lgandx/Responder#288]
Are there plans to extend Responder so that runs in python3? Currently I get errors about a mal-formed print command in the script, when I try to run it with pythons3.

**Comment by lgandx** [comment]
please provide the stacktrace

**Comment by servebeer** [comment]
So I am not a programmer, so I am not sure how to get a stacktrace with Python. If you can send me some instructions, I would be glad to do it. In the mean-time, here is a screenshot of the issue:
![responder error](https://github.com/user-attachments/assets/97d13c45-111c-4f25-8ddf-4393061b0daf)

**Comment by fgeek** [comment]
> If you can send me some instructions

How did you install Responder? Did it come via some operating system distribution?

If you do:
```
git clone https://github.com/lgandx/Responder.git
cd Responder
virtualenv venv
. ./venv/bin/activate
pip install -r requirements.txt
python3 Responder.py -I eth0 -A
```

Does it then work?

**Comment by fgeek** [comment]
You can also use tagged versions: https://github.com/lgandx/Responder/tags

**Comment by servebeer** [comment]
@fgeek Thanks for the suggestions. Cloning the repo fixed the issue for me. I am running it on Kali under Windows 11 (Windows Subsystem for Linux). Every now and then WSL causes some issues.

**Comment by fgeek** [comment]
> Cloning the repo fixed the issue for me

Alright. You can close this issue and create a new one related to WSL issues if needed. Happy hacking!
