### ISSUE TITLE
Issues with Multirelay and python 3.11

### ISSUE THREAD

**Issue by anance25** [lgandx/Responder#292]
I did some searching and there seems to be older issues referencing this error and Python3.10 but it sounded like those were resolved.  I'm running responder 3.1.5 and an updated copy of Kali linux.  

┌──(andy㉿haxor)-[/usr/share/responder/tools]
└─$ python --version
Python 3.11.9

┌──(andy㉿haxor)-[/usr/share/responder/tools]
└─$ sudo python MultiRelay.py -t 192.168.77.101 -u ALL

Responder MultiRelay 2.5 NTLMv1/2 Relay

Send bugs/hugs/comments to: laurent.gaffie@gmail.com
Usernames to relay (-u) are case sensitive.
To kill this script hit CTRL-C.

/*
Use this script in combination with Responder.py for best results.
Make sure to set SMB and HTTP to OFF in Responder.conf.

This tool listen on TCP port 80, 3128 and 445.
For optimal pwnage, launch Responder only with these 2 options:
-rv
Avoid running a command that will likely prompt for information like net use, etc.
If you do so, use taskkill (as system) to kill the process.
*/

Relaying credentials for these users:
['ALL']

/usr/share/responder/tools/MultiRelay.py:838: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  thread.setDaemon(True)

**Comment by lgandx** [comment]
Unfortunately, Multirelay is not anymore supported.
