### ISSUE TITLE
Random challenges get mixed up in Proxy_Auth

### ISSUE THREAD

**Issue by kithack** [lgandx/Responder#30]
I assumed that one Proxy_Auth instance would be created per TCP Connection. But it seems like a new Proxy_Auth instance is created per request. Therefore different Proxy_Auth instances and thus different challenges are used for packet type 0x1 and 0x3 of an NTLM authentication. 
All in all the hash written to the db is wrong because the challenge is wrong.
This seems like an architectural problem. For now i use a fixed challenge to circumvent that.
I expect the HTTP module to have the same problem but i haven't confirmed that.

Maybe the default challenge should be set to a fixed value until this is fixed.

**Comment by lgandx** [comment]
I can't reproduce here, all challenge I get are the good ones. Do you have an example scenario I could use to reproduce or a pcap?

**Comment by kithack** [comment]
Did you check if the resulting hash is valid? For example by putting it into jtr?
In my scenario there were several authentication attempts at the same time.
I will try to reproduce the error to give you more information.

**Comment by lgandx** [comment]
Yes I did, all hashes cracked successfully.

**Comment by lgandx** [comment]
Please let me know by re-opening this issue if you can re-reproduce at some point.
