### ISSUE TITLE
Missing servers/HTTPS.py file ?

### ISSUE THREAD

**Issue by falcon-lnhg** [lgandx/Responder#34]
I just updated Responder (from github - with gut pull) and in line 241 of Responder.py it is looking for servers/HTTPS.py (from servers.HTTP import HTTPS), but it is not found (ImportError: cannot import name HTTPS).
Is something missing here? A temporary workaround is to change HTTPS to Off in Responder.conf

**Comment by lgandx** [comment]
Fixed a typo :)

Thanks for your report!
