### ISSUE TITLE
Error Using Report.py

### ISSUE THREAD

**Issue by c0d3xpl0it** [lgandx/Responder#35]
Got the below error while running new Report.py module.

# python Report.py 
[+] Generating report...
[+] Unique lookups ordered by IP:
Traceback (most recent call last):
  File "Report.py", line 87, in <module>
    GetUniqueLookups(cursor)
  File "Report.py", line 61, in GetUniqueLookups
    res = cursor.execute("SELECT * FROM Poisoned WHERE ForName in (SELECT DISTINCT UPPER(ForName) FROM Poisoned) ORDER BY SentToIp, Poisoner")
sqlite3.OperationalError: no such table: Poisoned
root@kali:~/Responder#

**Comment by lgandx** [comment]
You probably git pull on a version you already used. To solve this issue, you need to:
rm Responder.db and lauch Responder again.

**Comment by c0d3xpl0it** [comment]
Thank you. It resolved the issue.
