### ISSUE TITLE
MultiRelay Encoding Errors 

### ISSUE THREAD

**Issue by ghelm** [lgandx/Responder#37]
Using something like this './MultiRelay.py -t 172.16.60.41 -u ALL -c whoami' on a german windows results in the following output:

> Retrieving information for 172.16.60.41...
> SMB signing: False
> Os version: 'Windows 7 Professional 7601 Service Pack 1'
> Hostname: 'PC01'
> Part of the 'XXX' domain
> [+] Setting up HTTP relay with SMB challenge: 9a6aa4fbb096455b
> [+] Received NTLMv2 hash from: 172.16.60.43 
> [+] Client info: ['Windows 7 Professional 7601 Service Pack 1', domain: 'XXX', signing:'False']
> [+] Username: bob is whitelisted, forwarding credentials.
> [+] SMB Session Auth sent.
> [+] Looks good, bob has admin rights on C$.
> [+] Authenticated.
> [+] Running command: whoami
> nt-autorit�t\system

The last line should actually read "nt-autorität\system" (german a umlaut).

**Comment by ghelm** [comment]
You could parse the output from the windows tool "chcp" on the victim to get the current codepage. The command seems to be around since MS-DOS: http://www.computerhope.com/chcphlp.htm

C:\Users\alice>chcp
Aktive Codepage: 850.

**Comment by lgandx** [comment]
Good call on the read/cmd output. Will be fixed in the next release ;)
