### ISSUE TITLE
MultiRelay params parsing issue

### ISSUE THREAD

**Issue by ghelm** [lgandx/Responder#38]
If you specify -c after -u for MultiRelay, the entered command will show up in the user whitelist array.

Example:
>./MultiRelay.py -t 172.16.60.41 -u ALL -c whoami

>Relaying credentials for these users:
>['ALL', 'whoami']

However, this doesn't seem to influece the behaviour of the tool.

>[+] Authenticated.
>[+] Running command: whoami

**Comment by lgandx** [comment]
Fixed! Will be pushed in the next version :)
