### ISSUE TITLE
MultiRelay: Unable to pwn IP if target_ip==request_source

### ISSUE THREAD

**Issue by ghelm** [lgandx/Responder#39]
Hi there,

if the MultiRelay target IP is the same IP as the request source, I'm unable to pwn the host. From my understanding, this should still work, if the user got the right permissions (which he does in my case (domadmin)).  Any idea why this fails? I didn't get any events in the Events Logs or any other kind of error. It just hangs at "SMB Session Auth sent."

Example:
> Retrieving information for 172.16.60.43...
> SMB signing: False
> Os version: 'Windows 7 Professional 7601 Service Pack 1'
> Hostname: 'VICTIM'
> Part of the 'XXX' domain
> [+] Setting up HTTP relay with SMB challenge: 304d7e8ae7fd8020
> [+] Received NTLMv2 hash from: 172.16.60.43 
> [+] Client info: ['Windows 7 Professional 7601 Service Pack 1', domain: 'XXX', signing:'False']
> [+] Username: bob is whitelisted, forwarding credentials.
> [+] SMB Session Auth sent.
> [+] Setting up HTTP relay with SMB challenge: 53e6bdf9e74a60a8
> [+] Received NTLMv2 hash from: 172.16.60.43 
> [+] Client info: ['Windows 7 Professional 7601 Service Pack 1', domain: 'XXX', signing:'False']
> [+] Username: bob is whitelisted, forwarding credentials.
> [+] SMB Session Auth sent.
> [+] Setting up HTTP relay with SMB challenge: dee8991c69c1f474
> [+] Received NTLMv2 hash from: 172.16.60.43 
> [+] Client info: ['Windows 7 Professional 7601 Service Pack 1', domain: 'XXX', signing:'False']
> [+] Username: bob is whitelisted, forwarding credentials.
> [+] SMB Session Auth sent.
> [+] Setting up HTTP relay with SMB challenge: 00d5290e757f2f6f
> [+] Received NTLMv2 hash from: 172.16.60.43 
> [+] Client info: ['Windows 7 Professional 7601 Service Pack 1', domain: 'XXX', signing:'False']
> [+] Username: bob is whitelisted, forwarding credentials.
> [+] SMB Session Auth sent.
> [+] Setting up HTTP relay with SMB challenge: e88b1f8cddebdaad
> [+] Received NTLMv2 hash from: 172.16.60.43 
> [+] Client info: ['Windows 7 Professional 7601 Service Pack 1', domain: 'XXX', signing:'False']
> [+] Username: bob is whitelisted, forwarding credentials.
> [+] SMB Session Auth sent.

**Comment by lgandx** [comment]
Thanks for your report! This issue is fixed and will be included in the next release.
Please note that reflective NTLM Relay is highly unlikely to work on modern network, since it has been patched in 2008.
