### ISSUE TITLE
RunFinger.py: GetHostnameAndDomainName failure on max domain length

### ISSUE THREAD

**Issue by joshuaskorich** [lgandx/Responder#44]
RunFinger.py contains an issue within GetHostnameAndDomainName that will prevent proper execution of RunFinger or MultiRelay when a systems uses the maximum 15 character domain/workgroup name:

```
def GetHostnameAndDomainName(data):
	try:
		DomainJoined, Hostname = tuple([e.replace('\x00','') for e in data[81:].split('\x00\x00\x00')[:2]])

```
When the maximum length domain/workgroup is used, the SMB response does not contain the standard delineation of \x00\x00\x00. As such, the Hostname will wind up empty, where the DomainJoined variable will contain the Domain concatenated with the Hostname. For example, configuring a workstation with:
workgroup: ABCDEFGHIJKLMNO 
hostname:123456789012345
```
$ ./tools/RunFinger.py -i 192.168.37.138
Retrieving information for 192.168.37.138...
SMB signing: False
Server Time: 2017-03-09 14:48:09
Os version: 'Windows 8.1 Enterprise 9600'
Lanman Client: 'Windows 8.1 Enterprise 6.3'
Machine Hostname: ''
This machine is part of the 'ABCDEFGHIJKLMNOAB123456789012345' domain
```
The function receives the following data (typecast hex):
0000008dff534d42720000000080000000000000000000000000000000003c1b000001001100000332000100041100000000010000000000fce3010079c8a0df1699d20168010848004439bab2cc928d184100420043004400450046004700480049004a004b004c004d004e004f0041423100320033003400350036003700380039003000310032003300340035000000

Logic looks for the split past [81:], however it does not exist. Instead we have:
Workgroup: 4100420043004400450046004700480049004a004b004c004d004e004f**004142**
Hostname: 3100320033003400350036003700380039003000310032003300340035000000

This issue prevents MultiRelay from working in situations that trigger the issue within RunFinger.py

**Comment by joshuaskorich** [comment]
Pull request #45 created

**Comment by lgandx** [comment]
Awesome man! I've integrated the change in the new version.
Thanks!
