### ISSUE TITLE
"Exception happened during processing of request"

### ISSUE THREAD

**Issue by braimee** [lgandx/Responder#47]
Hey there!

I was so pumped to try the new version of Responder that I rebuilt my Kali box and did nothing but the full rounds of apt-get update/upgrade to have the latest/greatest everything.

With the new Responder, what I'm finding is regardless of which mode I run it in, after any event happens I get a long "Exception happened..." error.  I scanned the README and don't think I'm missing any pre-reqs or config steps.  But I'll look at everything again and reply if it turns out to be PEBCAK :-)

![respond-to-this](https://cloud.githubusercontent.com/assets/17596787/24470443/8a7e8194-1484-11e7-9465-c3415d028876.png)

**Comment by lgandx** [comment]
Hi!

Simply delete Responder.db and run it again :)
This is happening because you've git pulled on a version you previously used ;)

Cheers

**Comment by braimee** [comment]
You're a wizard!  Thanks!
