### ISSUE TITLE
Cannot redirect to another IP

### ISSUE THREAD

**Issue by vysec** [lgandx/Responder#5]
Hi,

I edited the original SpiderLabs version to do:

python Responder.py -I eth0 -wF -i 8.8.8.8

To force all requests that come to me, to poison to a value of 8.8.8.8.

:( I think changes to ICMP-redirect.py broke this.

Is there any way you fix this?

**Comment by vysec** [comment]
Basically I'm trying to figure out where you are specifying the value to redirect to :(

**Comment by vysec** [comment]
Been trying to do it all night. I managed to force NBNS to 8.8.8.8 but cannot seem to poison LLMNR to 8,8.8.8

:( I wanted to use Responder as a redirector too...

**Comment by lgandx** [comment]
What you meant was poisoning all DNS, NBT-NS, LLMNR, MDNS queries with an external IP address of your choice, right?

**Comment by vysec** [comment]
Hi there.

Yes essentially

Maybe a parameter we can set. If we don't set it then it will poison it to our IP. If we set it then it should go to the target such as 8.8.8.8.

Responder acts as a way to respond to name queries. I hope that we can expand this so that we can control the response IP to use this in more sophisticated attacks.

**Comment by vysec** [comment]
Thanks for your hard work :)

**Comment by lgandx** [comment]
Cool make sense, working on it.

**Comment by vysec** [comment]
Sweet ;)

**Comment by lgandx** [comment]
All set, it's in the latest commit.

Thanks!

**Comment by vysec** [comment]
Fantastic. Looking forward for 2.3.2 and this change.

**Comment by vysec** [comment]
On another note. Can Responder do the relay of the proxy auth ntlm hashes?

**Comment by lgandx** [comment]
No, it can't right now.

**Comment by vysec** [comment]
Cool. Thanks for the amazing tool.
