### ISSUE TITLE
MultiRelay should ignore machine accounts

### ISSUE THREAD

**Issue by ad0nis** [lgandx/Responder#56]
If you use the -u ALL switch, MultiRelay should know to ignore usernames ending in $. In my experience, these are "machine hashes", and I've never seen them be usable to gain access to a system. It's just noise and authentication failures to send them at all as far as I can tell. (If this understanding is wrong, please correct me. I've never found any tutorials or guides that utilize the machine hash to compromise a system.)

**Comment by whitehat-zero** [comment]
It is possible for a system to be a member of a group and that group have admin rights on other systems. In this case you could use the original machine account's admin rights on other systems.
