### ISSUE TITLE
Work on interface which was not specified

### ISSUE THREAD

**Issue by TommyWhite** [lgandx/Responder#6]
./Responder.py -I eth1 -fwrdF 
eth0 192.168.1.0/24 
eth1 192.168.163.0/24

But instead of eth1, eth0 was engaged, but it should not.
As you will see below, Responder poisoned subnet which did not suppose to do.
Please, correct me if I am wrong. Also I may contibute this issue, If you will help me in localization the bug.
![image](https://cloud.githubusercontent.com/assets/14073162/18609537/2ac85374-7d0d-11e6-9cc0-f2e0bdff98fe.png)

**Comment by lgandx** [comment]
NBT-NS can be multicast depending of the configuration. (NetBIOS name resolution modes)
Could you provide more details on the environment please?

**Comment by lgandx** [comment]
I had several feedback about this. Will dig and submit a fix. Thank you.

**Comment by TommyWhite** [comment]
That would be great.

**Comment by lgandx** [comment]
All set! nice catch
