### ISSUE TITLE
RunFinger.py has a missing 'W' in Windows

### ISSUE THREAD

**Issue by tratteur** [lgandx/Responder#60]
$ ./RunFinger.py -i 192.168.1.0/24 -g
['192.168.1.13', Os:'indows Server 2008 R2 Standard 7600', Domain:'MAFEKING', Signing:'True', Time:'2017-08-18 14:20:52']

Purely cosmetic, obviously.

**Comment by lgandx** [comment]
I believe this was previously fixed :)
