### ISSUE TITLE
JTR cant load any hashes :()

### ISSUE THREAD

**Issue by GGGunrunner** [lgandx/Responder#64]
Responder: NBT-NS, LLMNR & MDNS Responder 2.3.3.6
John: 1.7.9 // 1.8.0

I just ran a quick test in my LAN and captured few HTTP and SMB requests.

But John cant load any hashes. Googled already, youtubed already - no real solutions. Any help?

Samples:
HTTP-NTLMv2-192.168.2.33.txt
Administrator::x1x1x:1122334455667788:7213E007EDB84BEDD93F240FDB4EC121:0101000000000000315145AB4ECFD2013D8D5700DD6CF077000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000000000000003000002664A63166E32CBAA3447EEA408DF45973965113A1AED458CF2F97470F339A5E0A00100000000000000000000000000000000000090000000000000000000000

SMB-NTLMv1-SSP-192.168.2.241.txt
Administrator::HOST:90784AF285BB06F600000000000000000000000000000000:5389E501F8B30519F09E3AA1BEFAF7DC25EF64218A65FF10:1122334455667788

SMB-NTLMv2-SSP-192.168.2.249.txt
Administrator::WIND3PL17LAJ:1122334455667788:61737F2E1ED94D5969546C8B25AE7776:0101000000000000CA1D35C4BED0D2011DF1919B2AD453860000000002000A0053004D0042003100320001000A0053004D0042003100320004000A0053004D0042003100320003000A0053004D0042003100320005000A0053004D00420031003200080030003000000000000000000000000030000087583DDD7BDF5834825CF32D94271794E6587C57294676F77C427EE0826419CF0A001000000000000000000000000000000000000900240063006900660073002F00390035002E003200310035002E00340035002E003200330036000000000000000000

HTTP-NTLMv2-192.168.2.170.txt
Administrator::RT1200:1122334455667788:D6A02E88F13E0A7051F124A5BCCBB048:0101000000000000CCE547EDFFFBD201F4C445323A5125E7000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C00080030003000000000000000000000000030000066DC82B65FF0ED9967E20ADC796929C2150AF6CA4F8E372A688631DF92B0D52A0A001000000000000000000000000000000000000900200048005400540050002F006F007400740069006D00650078002E0063006F006D000000000000000000

>># john HTTP-NTLMv2-192.168.2.170.txt
No password hashes loaded (see FAQ)

>># john --format=netntlmv2 HTTP-NTLMv2-192.168.2.170.txt
Unknown ciphertext format name requested

**Comment by Limpem** [comment]
Your hashes work fine with my version of John (1.8.0.13-jumbo-1-bleeding-1bc69682cb).
So it seems your problem lies with your version of john and not with responder.
You could recompile the latest source from the john the ripper github or try if you can crack the hashes using hashcat.

Hope this helps.
