### ISSUE TITLE
MultiRelay continues to relay same user hashes despite "Not forwarding anymore to prevent account lockout"

### ISSUE THREAD

**Issue by sdcampbell** [lgandx/Responder#76]
I cannot confirm that we experienced account lockouts because of MultiRelay, only that we were experiencing account lockouts while running it.

Notice that the REDACTED user returned logon_failure and said "Not forwarding anymore to prevent account lockout" yet it continues to forward that account:

[+] Setting up HTTP relay with SMB challenge: 47f6d8ef79000000
[+] Received NTLMv2 hash from: 10.11.1.159
[+] Client info: [‘indows 8.1 Enterprise 9600’, domain: ‘REDACTED’, signing:‘False’]
[+] Username: REDACTED is whitelisted, forwarding credentials.
**[+] User REDACTED\REDACTED previous login attempt returned logon_failure. Not forwarding anymore to prevent account lockout**

[+] Setting up HTTP relay with SMB challenge: 19ff304ed7000000
[+] Received NTLMv2 hash from: 10.11.1.159
[+] Client info: [‘indows 8.1 Enterprise 9600’, domain: ‘REDACTED’, signing:‘False’]
**[+] Username: REDACTED is whitelisted, forwarding credentials.
[+] User REDACTED\REDACTED previous login attempt returned logon_failure. Not forwarding anymore to prevent account lockout**

**Comment by lgandx** [comment]
So, that sequence of message is OK:
REDACTED is whitelisted, MultiRelay will initiate the process of sending credential. When that process starts, the first thing that happens is checking is there was a previous auth that failed for that users, when you see that message " previous login attempt returned logon_failure. Not forwarding anymore to prevent account lockout" the connection is actually being dropped and nothing gets forwarded by MultiRelay
