### ISSUE TITLE
Strange characters in captured username

### ISSUE THREAD

**Issue by cogphn** [lgandx/Responder#77]
I'm seeing this happening alot (see screenshot) is this normal?

![responder_strange_username](https://user-images.githubusercontent.com/7780019/37249077-72fd4ea4-24b6-11e8-8889-2b563529de97.PNG)

**Comment by cogphn** [comment]
here are some other examples from another client. Not sure why it is happening:

![image](https://user-images.githubusercontent.com/7780019/37427268-475c82c4-279f-11e8-8380-ca324ccc7690.png)

**Comment by joefizz** [comment]
I;m getting this exact same issue.  This is using the version of responder that is packaged with Kali 2018.1 (and updated).  NBT-NS, LLMNR & MDNS Responder 2.3.3.9

**Comment by cnotin** [comment]
Hello @cogphn and @joefizz, if you have the occasion try again with the latest version from the master branch that includes PR #89.
Let us know if it fixes it!
