### ISSUE TITLE
Responder not poisoning w/latest and greatest Kali?

### ISSUE THREAD

**Issue by braimee** [lgandx/Responder#87]
Hello!

I just grabbed a fresh Kali (2018.4), ran a full round of apt-get update/upgrade, and then installed Responder and ran it.  Then on my Windows machines on the same subnet, I started browsing to various resources (\\blah, \\blah2, etc.).  And then I experienced something I'd never seen before...it's like Responder was "responding" but not actually capturing hashes (see screenshot):

![responder](https://user-images.githubusercontent.com/17596787/48658240-033e8d80-ea04-11e8-8f9d-1b842fac853f.png)

Tomorrow I'll try another Linux box and another network just to do a sanity check (it's 1 a.m. and my fatigue could be the root cause) but just thought I'd submit this in case you'd ever seen a similar behavior.

Thanks,
Brian

**Comment by lgandx** [comment]
Hi Brian, 

Were you able to you confirm this issue?
On my side, its running fine on all Windows versions.

**Comment by braimee** [comment]
Hi there!  

Sorry for the delay.  I just built a new Kali box on a NUC running ESXi and deployed at a site today.  I'm feeling like I'm taking crazy pills as my issue remains(!).  I haven't done anything but run apt updates and edit the .conf file to turn off SMB and HTTP.  I run responder with -wrf and it poisons all day according to the output, but never actually captures hashes.  I need to sleep because it's been a long day, and will report back tomorrow.  Could very well be a "duh!" thing as I think you'd be hearing about this if there was a Kali/distro problem.

Thanks,
Brian

**Comment by lgandx** [comment]
Ok, so if you turned SMB and HTTP Off, it's normal Responder doesn't grab anything since you disabled these rogue auth servers. This type of configuration should always be run with MultiRelay in background. If you are not running it, please just restore these settings to On and you will start seeing some hashes.

**Comment by braimee** [comment]
Sorry I totally forgot to write back to this.  Yes, it was a derp moment and I had to give myself a forehead slap.  Time for more sleep.  Thanks for your help!
