### ISSUE TITLE
Responder disrupting the network and cant capture hashes / wpad also doesnt capture

### ISSUE THREAD

**Issue by xdu8026** [lgandx/Responder#90]
1. I found this article explaining the situation in the lab the best:
https://markclayton.github.io/where-are-my-hashes-responder-observations.html
2. when testing responder in the lab with options -wPfv
responder poisons LLMNR and NBT-NS for valid names but doesnt get the hash, also while continuing to poison it disrupts the network for these hosts that ask.
When the win 10 machine requests wpad - responder posions and give output WPAD(no auth) file sent but HTTP is User-Agent        : WinHttp-Autoproxy-Service/5.1
and again no hash.
3. I dont know if the options I test are wrong, tried to emulate a scenario which wants to be as silent as it can get and obtain hashes, thats why I didnt user -r or -d so not to disrupt network, but it disrupts it without them too. Also used -P instead of -F to not to force a login prompt on the machine but get the hashes silently but it didnt receive any.

Is the wpad -w option not working on IE 11 because on default state it blocks proxy configurations as stated in the article?
Also since posioning valid requests causes conflict as in the article and breaks the network for those valid requests, how can the hashes be captured without breaking it, is it needed to use different options or its something else

**Comment by lgandx** [comment]
Best would be to run it as: -rFvw
Let me know if it worked.

**Comment by lgandx** [comment]
Responder's attacks are adaptive and sequentials, I personally starts with -A
When I get a good view of the network layout; -rPv
Depending of the output, I might switch to ARP spoof, with prerouting IP tables rules for some specific hosts and ports and use -rbv
Again, it always depends of the network layout... and users, and environment. It's a case by case thing.
