### ISSUE TITLE
Some generated hashes are uncrackable with correct password

### ISSUE THREAD

**Issue by Limpem** [lgandx/Responder#94]
Some hashes that get picked up by responder are uncrackable while others work fine from the same system.
As an example I have setup a testsytem with the username admin and the password Admin.
The HTTP-NTLMv2 hashes all seem to crack fine with both hashcat and john the ripper:

> admin::-PC:8d485080abc7b3b2:CA8FD6E70548EE7CEDDFEA7768B6EF7D:01010000000000009BD803874ED3D4013CBEE50D57E6B496000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000002000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009002C0048005400540050002F006F006300730070002E00640069006700690063006500720074002E0063006F006D000000000000000000
>admin::-PC:78758d070a92662e:5D1FF5F1444ACA1CF16C0BDCFD8E9EB1:010100000000000087C0119A4ED3D4013B28AA15B7F1322B000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000002000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009002C0048005400540050002F006F006300730070002E00640069006700690063006500720074002E0063006F006D000000000000000000

The Proxy NTLMv2 hashes however are a mixed bag, of the following 14 hashes, only 5 can be cracked with both hashcat and john the ripper:

 >admin::-PC:5617c990be375d54:EA1B82B1C759C8B7213524EDFB5978DB:0101000000000000212C76724ED3D401034BC10AB390F075000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000002000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009001A0048005400540050002F00700072006F00780079007300720076000000000000000000
>admin::-PC:5617c990be375d54:EA1B82B1C759C8B7213524EDFB5978DB:0101000000000000212C76724ED3D401034BC10AB390F075000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000002000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009001A0048005400540050002F00700072006F00780079007300720076000000000000000000
>admin::-PC:1a9919838d92f877:8F98F63FC2F31FF2DCD86CA19E054FF9:01010000000000006D8948744ED3D40192BF40FCAFEDDB6A000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000002000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009001A0048005400540050002F00700072006F00780079007300720076000000000000000000
>admin::-PC:42d59d2c2ca13573:58B95075D94231E6EDCB3051D937D4F0:01010000000000005AAA1F764ED3D4010CF24F4318D05C60000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000002000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009001A0048005400540050002F00700072006F00780079007300720076000000000000000000
>admin::-PC:243e608a11d77af8:6E20830988F28E3BDE747F3FF72A6BDF:0101000000000000A1D0B0764ED3D4019FA48360F96644DA000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000002000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009001A0048005400540050002F00700072006F00780079007300720076000000000000000000
>admin::-PC:6226721ce586ed6b:74C0FA47A4D410167C255AC7B77D2B5D:0101000000000000C10245804ED3D401BDEBC0F871DCE8AE000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000002000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009001A0048005400540050002F00700072006F00780079007300720076000000000000000000
>admin::-PC:92308081af169c5e:635B43A88F5046C9E3C9BB38120D5798:0101000000000000C18240864ED3D401B77CE2F4D17FECAE000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000001000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009001A0048005400540050002F00700072006F00780079007300720076000000000000000000
>admin::-PC:2f2b1b7704d40de3:5F75C86F9BD8A2C16C5B447A64DCA452:010100000000000074C241874ED3D4017D4D1678BF9D4CA8000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000001000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009001A0048005400540050002F00700072006F00780079007300720076000000000000000000
>admin::-PC:e10d5576a82058ab:8878D43A6A398769C08FE43CB9A3DE8E:0101000000000000136045884ED3D401439AAC237E3869D9000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000001000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009001A0048005400540050002F00700072006F00780079007300720076000000000000000000
>admin::-PC:f1b21743639acfc0:4B524105674FB96CB8E4C627E51AF36B:0101000000000000B89546894ED3D40100D752C49D32310F000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000001000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009001A0048005400540050002F00700072006F00780079007300720076000000000000000000
>admin::-PC:7186b82956b3bbe0:B18F2663E545FE02F1FC95729A34C0FF:01010000000000006F1EC1864ED3D40177D6B935F28943E1000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000001000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009001A0048005400540050002F00700072006F00780079007300720076000000000000000000
>admin::-PC:89badedd3f2cffb9:8B18364764C91AF916ADCE7563EB16E5:0101000000000000F8FAC5884ED3D40159721AFCEA8BB8C7000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000001000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009001A0048005400540050002F00700072006F00780079007300720076000000000000000000
>admin::-PC:c9fa2b17e135cfb5:95CF79647ADAD480B1B4CC2855266080:01010000000000006433C7894ED3D401541BEC392757E9AF000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000001000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009001A0048005400540050002F00700072006F00780079007300720076000000000000000000
>admin::-PC:e9dcb2d93a008f3f:3AF86BEBEEBEF0B85272ECA0CD3E7451:0101000000000000BE58C2874ED3D401A26A327A660C9A72000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000001000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009001A0048005400540050002F00700072006F00780079007300720076000000000000000000
>admin::-PC:70a163af85a5ac83:0E6DA34CE364035400CD53158B3F63CD:01010000000000006BD3478A4ED3D401F7375EEFAE584F7C000000000200060053004D0042000100160053004D0042002D0054004F004F004C004B00490054000400120073006D0062002E006C006F00630061006C000300280073006500720076006500720032003000300033002E0073006D0062002E006C006F00630061006C000500120073006D0062002E006C006F00630061006C0008003000300000000000000001000000001000009558182611295353E348FE30B962C47746F5DA00F1919E3555424EE04465762C0A0010000000000000000000000000000000000009001A0048005400540050002F00700072006F00780079007300720076000000000000000000

I grabbed those hashes with the following responder options: -w -r -d -P

**Comment by lgandx** [comment]
This has been resolved in a previous commit. Thanks for your report!
