### ISSUE TITLE
Mac OSX

### ISSUE THREAD

**Issue by CyberEYMS** [lgandx/Responder#97]
Does the Responder work on Mac targets?
I tested the tool on "Windows 10" and it worked. But on "macOS Mojave" it didn't.
I ran the command on kali linux system : "python Responder.py -i 'my ip' -I 'interface'"

**Comment by bert128** [comment]
I suspect this is down to issue #102, i had the same problem and tracked it down to macos sending the mdns requests out using ipv6 while responder only listens for ipv4.
