### ISSUE TITLE
Help understanding HTTP-NTLMv1 hash captures

### ISSUE THREAD

**Issue by braimee** [lgandx/Responder#98]
Hello,

This isn't an issue with Responder, but just wondering if you could educate me a bit more on the HTTP-NTLMv1 captures.  I ran Responder on a client network and many machines sent a HTTP-NTLMv1 hash formatted like this:
````
SERVICE-ACCOUNT::MACHINE-NAME:(48 characters):(48 characters):(16 characters)
````

The SERVICE-ACCOUNT was the same for all captures, the MACHINE-NAME and everything else in the capture was different per capture.  Yet...all these hashes cracked to the same password.

The client wants to know what it is on all these systems that is contributing to this vulnerability and how to fix it.  I'm not really sure what's going on to cause the machines to cough up this specific type of hash, and not seeing a lot on the Internet.  Could you point me in the right direction?

Thanks,
Brian

**Comment by lgandx** [comment]
This user is usually used for establishing schannels sessions, as far as i know it's useless.
